#pragma once

#include <QString>

namespace EditorTheme
{
inline QString Stylesheet()
{
    return QStringLiteral(
        "QMainWindow#EditorMainWindow, QWidget#EditorRoot {"
        "  background: #1e1e26;"
        "  color: #d5d3dc;"
        "  font-family: 'Segoe UI';"
        "  font-size: 13px;"
        "}"
        "QMenuBar {"
        "  background: #24242d;"
        "  color: #d5d3dc;"
        "  border-bottom: 1px solid #44404d;"
        "  padding: 2px 6px;"
        "}"
        "QMenuBar::item {"
        "  background: transparent;"
        "  padding: 5px 10px;"
        "  border-radius: 3px;"
        "}"
        "QMenuBar::item:selected, QMenuBar::item:pressed {"
        "  background: #493b48;"
        "  color: #ead4df;"
        "}"
        "QMenu {"
        "  background: #282932;"
        "  color: #d5d3dc;"
        "  border: 1px solid #44404d;"
        "}"
        "QMenu::item:selected {"
        "  background: #493b48;"
        "  color: #ead4df;"
        "}"
        "QToolBar#EditorToolbar {"
        "  background: #292932;"
        "  border-bottom: 1px solid #44404d;"
        "  spacing: 8px;"
        "  padding: 4px 10px;"
        "}"
        "QToolButton, QPushButton.EditorToolButton {"
        "  background: #33303b;"
        "  color: #c6c1cd;"
        "  border: 1px solid #504553;"
        "  border-radius: 3px;"
        "  padding: 5px 9px;"
        "}"
        "QToolButton:hover, QPushButton.EditorToolButton:hover {"
        "  background: #40323e;"
        "  border-color: #6b4e60;"
        "  color: #ead4df;"
        "}"
        "QToolButton:checked, QPushButton.EditorToolButton:checked {"
        "  background: #60485c;"
        "  border-color: #b58ba1;"
        "  color: #ffe4f0;"
        "}"
        "QPushButton#PlayButton {"
        "  background: #40323e;"
        "  border: 1px solid #67505f;"
        "  color: #e4b9cd;"
        "  min-width: 34px;"
        "  min-height: 28px;"
        "  border-radius: 3px;"
        "}"
        "QPushButton#PlayButton:checked {"
        "  background: #4b3b49;"
        "  border-color: #b48ca2;"
        "  color: #f1dae5;"
        "}"
        "QComboBox, QLineEdit {"
        "  background: #202129;"
        "  color: #d5d3dc;"
        "  border: 1px solid #44404d;"
        "  border-radius: 3px;"
        "  padding: 4px 8px;"
        "  min-height: 22px;"
        "}"
        "QComboBox::drop-down { border: none; width: 18px; }"
        "QComboBox QAbstractItemView {"
        "  background: #282932;"
        "  color: #d5d3dc;"
        "  selection-background-color: #493b48;"
        "  border: 1px solid #44404d;"
        "}"
        "QSplitter::handle {"
        "  background: #44404d;"
        "}"
        "QSplitter::handle:horizontal { width: 5px; }"
        "QSplitter::handle:vertical { height: 5px; }"
        "QWidget#HierarchyPanel, QWidget#InspectorPanel, QWidget#ViewportPanel, QWidget#GraphDock {"
        "  background: #282932;"
        "  border: 1px solid #44404d;"
        "}"
        "QLabel#PanelHeader {"
        "  background: #25252e;"
        "  color: #d5d3dc;"
        "  padding: 6px 10px;"
        "  border-bottom: 1px solid #44404d;"
        "  font-weight: 600;"
        "}"
        "QTabWidget::pane {"
        "  border: none;"
        "  background: #25262e;"
        "}"
        "QTabBar::tab {"
        "  background: transparent;"
        "  color: #95909e;"
        "  padding: 7px 10px;"
        "  border: none;"
        "  border-bottom: 2px solid transparent;"
        "}"
        "QTabBar::tab:selected {"
        "  color: #ead4df;"
        "  border-bottom: 2px solid #c496ad;"
        "  background: #2c2a34;"
        "}"
        "QTabBar::tab:hover {"
        "  color: #d5d3dc;"
        "  background: #33303b;"
        "}"
        "QTreeWidget {"
        "  background: #23242c;"
        "  color: #d5d3dc;"
        "  border: none;"
        "  outline: none;"
        "}"
        "QTreeWidget::item { padding: 4px 6px; }"
        "QTreeWidget::item:selected {"
        "  background: #493b48;"
        "  color: #ead4df;"
        "}"
        "QTreeWidget::item:hover { background: #33303b; }"
        "QListWidget {"
        "  background: #23242c;"
        "  color: #d5d3dc;"
        "  border: none;"
        "}"
        "QListWidget::item { padding: 6px 8px; }"
        "QListWidget::item:selected { background: #493b48; color: #ead4df; }"
        "QTextEdit, QPlainTextEdit {"
        "  background: #202129;"
        "  color: #d5d3dc;"
        "  border: 1px solid #44404d;"
        "  border-radius: 3px;"
        "}"
        "QStatusBar {"
        "  background: #24242d;"
        "  color: #95909e;"
        "  border-top: 1px solid #44404d;"
        "}"
        "QLabel#ViewportPlaceholder {"
        "  background: #1a1a22;"
        "  color: #95909e;"
        "  border: 1px dashed #534050;"
        "  border-radius: 4px;"
        "}"
        "QLabel#BrandLabel {"
        "  color: #d5d3dc;"
        "  font-weight: 700;"
        "  padding-left: 4px;"
        "}"
        "QLabel#BrandAccent { color: #c496ad; font-weight: 700; }"
        "QLabel#MutedLabel { color: #95909e; }"
        "QLabel#RoseLabel { color: #c496ad; }"
        "QFrame#LiveStrip {"
        "  background: #22212b;"
        "  border-top: 1px solid #44404d;"
        "}"
        "QWidget#ReflectionInspector QPushButton {"
        "  background: #33303b;"
        "  color: #c6c1cd;"
        "  border: 1px solid #504553;"
        "  border-radius: 3px;"
        "  padding: 5px 9px;"
        "}"
        "QWidget#ReflectionInspector QPushButton:hover {"
        "  background: #40323e;"
        "  border-color: #6b4e60;"
        "  color: #ead4df;"
        "}"
        "QWidget#ReflectionInspector QPushButton:disabled {"
        "  background: #2a2a33;"
        "  color: #6a6570;"
        "  border-color: #3a3842;"
        "}"
        "QWidget#ReflectionInspector QLabel {"
        "  color: #d5d3dc;"
        "}"
    );
}
}
