import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Icon} from './StudioParts.jsx';
import './editorContextMenu.css';

export default function EditorContextMenu({x,y,title,items,onClose}){
 const ref=useRef(),[query,setQuery]=useState(''),[submenu,setSubmenu]=useState(null),[submenuPosition,setSubmenuPosition]=useState({}),subRef=useRef(),[position,setPosition]=useState({left:x,top:y});
 const searched=items.flatMap(item=>item.children?[item,...item.children.map(child=>({...child,group:item.label}))]:[item]);
 const visible=(query?searched.filter(item=>!item.children):items).filter(item=>(item.label+' '+(item.group||'')).toLowerCase().includes(query.toLowerCase()));
 useLayoutEffect(()=>{const box=ref.current.getBoundingClientRect();setPosition({left:Math.max(8,Math.min(x,window.innerWidth-box.width-8)),top:Math.max(8,Math.min(y,window.innerHeight-box.height-8))});},[x,y,query,items.length]);
 const openSubmenu=(item,trigger,focus=false)=>{const rect=trigger.getBoundingClientRect();setSubmenu({item,trigger,focus,top:rect.top});};
 useLayoutEffect(()=>{if(!submenu||!subRef.current)return;const box=subRef.current.getBoundingClientRect(),parent=ref.current.getBoundingClientRect();setSubmenuPosition({left:parent.right+box.width+8<=window.innerWidth?parent.right+3:Math.max(8,parent.left-box.width-3),top:Math.max(8,Math.min(submenu.top,window.innerHeight-box.height-8))});if(submenu.focus)subRef.current.querySelector('button')?.focus();},[submenu,position]);
 useEffect(()=>{const previous=document.activeElement;ref.current.querySelector('input')?.focus();const dismiss=e=>{if(!ref.current?.contains(e.target))onClose();};const close=()=>onClose();window.addEventListener('pointerdown',dismiss,true);window.addEventListener('resize',close);window.addEventListener('blur',close);return()=>{window.removeEventListener('pointerdown',dismiss,true);window.removeEventListener('resize',close);window.removeEventListener('blur',close);if(previous?.isConnected)previous.focus({preventScroll:true});};},[onClose]);
 return createPortal(<div className="editor-context-menu" ref={ref} style={position} role="dialog" aria-label={title} onContextMenu={e=>e.preventDefault()} onKeyDown={e=>{
  if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}
  if(e.key==='ArrowRight'){const item=items.find(item=>item.label===e.target.dataset.submenu);if(item){e.preventDefault();openSubmenu(item,e.target,true);}}
  if(e.key==='ArrowLeft'&&submenu){e.preventDefault();submenu.trigger.focus();setSubmenu(null);}
  if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const scope=e.target.closest('.editor-context-submenu')||ref.current;const controls=[...scope.querySelectorAll('input,button:not(:disabled)')].filter(control=>scope!==ref.current||!control.closest('.editor-context-submenu')),index=controls.indexOf(document.activeElement);controls[(index+(e.key==='ArrowDown'?1:-1)+controls.length)%controls.length]?.focus();}
  if(e.key==='Enter'&&e.target.tagName==='INPUT'){e.preventDefault();const item=visible.find(item=>!item.disabled);if(item){if(item.children){const trigger=[...ref.current.querySelectorAll('[data-submenu]')].find(button=>button.dataset.submenu===item.label);if(trigger)openSubmenu(item,trigger,true);}else{onClose();item.action();}}}
 }}><strong>{title}</strong><label><Icon name="Search" size={14}/><input aria-label="Поиск в контекстном меню" placeholder="Поиск…" value={query} onChange={e=>{setQuery(e.target.value);setSubmenu(null);}}/></label><div role="menu" aria-label={title}>{visible.map((item,index)=><React.Fragment key={item.id||item.label}>{item.group&&item.group!==visible[index-1]?.group&&<small className="editor-context-group">{item.group}</small>}<button role="menuitem" disabled={item.disabled} data-submenu={item.children?item.label:undefined} aria-haspopup={item.children?"menu":undefined} aria-expanded={item.children?submenu?.item===item:undefined} onMouseEnter={e=>item.children?openSubmenu(item,e.currentTarget):setSubmenu(null)} onClick={e=>{if(item.children){openSubmenu(item,e.currentTarget,true);return;}onClose();item.action();}}><Icon name={item.icon||'Plus'} size={16}/><span>{item.label}</span>{item.shortcut&&<kbd>{item.shortcut}</kbd>}{item.children&&<Icon name="ChevronRight" size={14}/>}</button></React.Fragment>)}{!visible.length&&<p>Ничего не найдено</p>}</div>{submenu&&<div className="editor-context-submenu" style={submenuPosition} ref={subRef} role="menu" aria-label={submenu.item.label}>{submenu.item.children.map(item=><button key={item.label} role="menuitem" disabled={item.disabled} onClick={()=>{onClose();item.action();}}><Icon name={item.icon||'Box'} size={16}/><span>{item.label}</span></button>)}</div>}</div>,document.body);
}
