import React,{useState} from 'react';
import {Icon} from './StudioParts.jsx';
import {ANSWER_VARIABLE,variableName} from './choiceModel.js';
import {VARIABLE_TYPES,variableType} from './variableModel.js';
import './blueprintVariables.css';
export default function BlueprintVariables({project,onEdit,onAddNode,onInspect,selectedVariable,disabled}){
 const [query,setQuery]=useState(''),[error,setError]=useState(''),[collapsed,setCollapsed]=useState(false);
 const active=selectedVariable,ids=Object.keys(project.variables||{}),system=active===ANSWER_VARIABLE;
 const select=id=>{setError('');onInspect?.(id);};
 if(collapsed)return <aside className="bp-variables collapsed"><button title="Показать переменные" onClick={()=>setCollapsed(false)}><Icon name="Database" size={18}/></button></aside>;
 return <aside className="bp-variables" aria-label="Переменные Blueprint"><header><strong>Мой Blueprint</strong><button title="Свернуть переменные" onClick={()=>setCollapsed(true)}><Icon name="PanelLeftClose" size={16}/></button></header><div className="bp-variable-title"><strong>Переменные</strong><button title="Создать переменную" disabled={disabled} onClick={()=>{let i=1;while(Object.hasOwn(project.variables,'Переменная '+i))i++;const id='Переменная '+i;const issue=onEdit(id,{type:'boolean',value:false});if(!issue)select(id);else setError(issue);}}><Icon name="Plus" size={16}/></button></div><input aria-label="Поиск переменных" placeholder="Поиск переменных…" value={query} onChange={e=>setQuery(e.target.value)}/>{!ids.length&&<p className="bp-variables-empty">Переменных пока нет. Нажмите +, чтобы создать свою.</p>}<div className="bp-variable-list" role="listbox" aria-label="Переменные проекта">{ids.filter(id=>(id+' '+variableName(id)).toLowerCase().includes(query.toLowerCase())).map(id=><button role="option" aria-selected={active===id} key={id} className={'bp-variable-item type-'+variableType(project,id)} draggable={!disabled} onDragStart={e=>{e.dataTransfer.setData('application/sacura-variable',id);e.dataTransfer.effectAllowed='copy';}} onClick={()=>select(id)} onDoubleClick={()=>!disabled&&onAddNode(id,'variable')}><i/><span>{variableName(id)}{variableName(id)!==id&&<small>{id}</small>}</span><small>{VARIABLE_TYPES.find(([v])=>v===variableType(project,id))?.[1].split(' · ')[0]||'Текст'}</small></button>)}</div>{project.chapters.some(c=>c.beats.some(b=>b.variable===ANSWER_VARIABLE))&&<div className="bp-variable-system"><button onClick={()=>select(ANSWER_VARIABLE)} className={system?'selected':''}><Icon name="LockKeyhole" size={13}/>Последний ответ игрока</button></div>}{error&&<p role="alert">{error}</p>}<footer>Перетащите переменную на граф.<br/>Ctrl: Get · Alt: Set<br/>Двойной щелчок: Get</footer></aside>;
}
