import FunctionParameters from './FunctionParameters.jsx';
import React,{useState,useMemo,useEffect} from 'react';
import {ReactFlow,Background,Controls,Handle,Position} from '@xyflow/react';
import {Button} from './StudioParts.jsx';
import {uid} from './model.js';
import {newBlueprintFunction} from './blueprintFunctions.js';
import {t as tr,useLocale} from './i18n.jsx';
import {ValueField} from './ChoiceInspector.jsx';
import GameplayCommandFields,{GameField,GameSelect,JsonValue} from './GameplayCommandFields.jsx';
const kinds={set:'Set · Записать значение',branch:'If · Если',array:'Массив',call:'Вызвать функцию',command:'Игровая команда',return:'Вернуть результат'};
const ops={literal:'Значение',get:'Переменная / поле',add:'Сложить',sub:'Вычесть',mul:'Умножить',div:'Разделить',eq:'Равно',ne:'Не равно',lt:'Меньше',gt:'Больше',and:'И',or:'Или',not:'Не',field:'Поле структуры',at:'Элемент массива',length:'Длина массива',array:'Создать массив',struct:'Создать структуру'};
function Expr({value,onChange,label='Значение',depth=0}){const op=value?.op||'literal';return <div className="game-expression"><GameSelect label={label} value={op} options={Object.entries(ops)} onChange={op=>onChange(op==='literal'?0:op==='get'?{op,path:'global.hp'}:{op,a:0,b:0,field:'',values:[],fields:{}})}/>{op==='literal'?<><GameSelect label="Тип значения" value={Array.isArray(value)?'array':value&&typeof value==='object'?'struct':typeof (value??0)} options={[["number","Число"],["string","Текст"],["boolean","Да / нет"],["array","Массив"],["struct","Структура"]]} onChange={type=>onChange(({number:0,string:'',boolean:false,array:[],struct:{}})[type])}/><ValueField label={label} type={Array.isArray(value)?'array':value&&typeof value==='object'?'struct':typeof (value??0)} value={value??0} onChange={onChange}/></>:op==='get'?<GameField label="Путь значения"><input placeholder="global.hp / args.amount / local.result" value={value.path||''} onChange={e=>onChange({...value,path:e.target.value})}/></GameField>:['array','struct'].includes(op)?<JsonValue label={op==='array'?'Элементы массива':'Поля структуры'} value={op==='array'?value.values||[]:value.fields||{}} onChange={v=>onChange({...value,[op==='array'?'values':'fields']:v})}/>:<>{depth<4?<Expr label="A" value={value.a} depth={depth+1} onChange={a=>onChange({...value,a})}/>:<JsonValue label="A" value={value.a} onChange={a=>onChange({...value,a})}/>} {!['not','length','field'].includes(op)&&(depth<4?<Expr label="B / индекс" value={value.b} depth={depth+1} onChange={b=>onChange({...value,b})}/>:<JsonValue label="B" value={value.b} onChange={b=>onChange({...value,b})}/>)}{op==='field'&&<GameField label="Поле структуры"><input value={value.field||''} onChange={e=>onChange({...value,field:e.target.value})}/></GameField>}</>}</div>;}
function FunctionNode({data}){return <div className="function-node"><Handle type="target" position={Position.Top}/><strong>{data.entry?'▶ ':''}{tr(kinds[data.node.kind])}</strong><span>{data.node.name}</span>{data.node.kind!=='return'&&(data.node.kind==='branch'?<><Handle id="true" type="source" position={Position.Bottom} style={{left:'30%'}}/><Handle id="false" type="source" position={Position.Bottom} style={{left:'70%'}}/></>:<Handle id="next" type="source" position={Position.Bottom}/>)}</div>;}
const nodeTypes={function:FunctionNode};
export default function BlueprintFunctionWorkspace({project,onChange,requestedId}){useLocale();const [selected,setSelected]=useState(''),[nodeId,setNodeId]=useState(''),[error,setError]=useState('');useEffect(()=>{if(requestedId){setSelected(requestedId);setNodeId('');}},[requestedId]);const f=project.functions.find(f=>f.id===selected)||project.functions[0],n=f?.nodes.find(n=>n.id===nodeId);const edit=fn=>onChange(p=>fn(p.functions.find(x=>x.id===f.id))),patch=v=>edit(f=>Object.assign(f.nodes.find(x=>x.id===n.id),v));const options=[['','Завершить'],...(f?.nodes||[]).filter(x=>x.id!==n?.id).map(x=>[x.id,x.name||kinds[x.kind]])];const nodes=useMemo(()=>f?.nodes.map((node,i)=>({id:node.id,type:'function',position:node.position||{x:(i%3)*250,y:Math.floor(i/3)*160},selected:node.id===nodeId,data:{node,entry:f.entry===node.id}}))||[],[f,nodeId]),edges=f?.nodes.flatMap(n=>['next','trueNext','falseNext'].filter(k=>n[k]).map(k=>({id:n.id+k,source:n.id,target:n[k],sourceHandle:k==='trueNext'?'true':k==='falseNext'?'false':'next',label:k==='trueNext'?tr('Да'):k==='falseNext'?tr('Нет'):undefined})))||[];
 return <div className="function-workspace"><header><GameSelect label="Функция Blueprint" value={f?.id} options={project.functions.map(f=>[f.id,f.name])} onChange={id=>{setSelected(id);setNodeId('');}}/><Button icon="Plus" onClick={()=>{const x=newBlueprintFunction();onChange(p=>p.functions.push(x));setSelected(x.id);}}>{tr('Создать функцию')}</Button></header>{!f?<p>{tr('Функции можно вызывать из событий, правил и других функций.')}</p>:<><div className="function-body"><div className="function-graph"><ReactFlow key={f.id} nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView onNodeClick={(_,n)=>setNodeId(n.id)} onNodeDragStop={(_,node)=>edit(f=>{f.nodes.find(x=>x.id===node.id).position=node.position;})} onConnect={c=>{if(!c.source||!c.target)return;if(c.source===c.target){setError(tr('Для повторения используйте правило «Периодически».'));return;}edit(f=>{const n=f.nodes.find(n=>n.id===c.source);n[c.sourceHandle==='true'?'trueNext':c.sourceHandle==='false'?'falseNext':'next']=c.target;});}} onEdgesDelete={edges=>edit(f=>{for(const e of edges){const n=f.nodes.find(n=>n.id===e.source),key=e.sourceHandle==='true'?'trueNext':e.sourceHandle==='false'?'falseNext':'next';n[key]='';}})}><Background/><Controls/></ReactFlow></div><aside><GameField label="Имя функции"><input value={f.name} onChange={e=>edit(f=>{f.name=e.target.value;})}/></GameField><GameSelect label="Точка входа" value={f.entry} options={f.nodes.map(n=>[n.id,n.name||kinds[n.kind]])} onChange={entry=>edit(f=>{f.entry=entry;})}/><details><summary>{tr('Параметры и локальные переменные')}</summary><FunctionParameters fn={f} onChange={values=>edit(f=>Object.assign(f,values))}/></details>
 <GameSelect label="Добавить ноду" value="" options={[["","Выберите…"],...Object.entries(kinds)]} onChange={kind=>{if(!kind)return;const id=uid('fn-node');edit(f=>f.nodes.push({id,kind,name:kinds[kind],path:'local.result',value:0,condition:{op:'gt',a:{op:'get',path:'args.amount'},b:0},operation:'push',index:0,next:'',command:{command:'damage',value:{amount:25}}}));setNodeId(id);}}/>
 {n&&<><h3>{tr(kinds[n.kind])}</h3><GameField label="Имя ноды"><input value={n.name} onChange={e=>patch({name:e.target.value})}/></GameField>{['set','array'].includes(n.kind)&&<GameField label="Записать в"><input value={n.path||''} placeholder="global.inventory / local.result" onChange={e=>patch({path:e.target.value})}/></GameField>}{['set','return'].includes(n.kind)&&<Expr value={n.value} onChange={value=>patch({value})}/>}{n.kind==='branch'&&<><Expr label="Условие" value={n.condition} onChange={condition=>patch({condition})}/>{['trueNext','falseNext'].map(key=><GameSelect key={key} label={key==='trueNext'?'Если да':'Если нет'} value={n[key]} options={options} onChange={id=>patch({[key]:id})}/>)}</>}{n.kind==='array'&&<><GameSelect label="Операция" value={n.operation} options={[["push","Добавить"],["remove","Удалить"],["set","Заменить"]]} onChange={operation=>patch({operation})}/>{n.operation!=='push'&&<Expr label="Индекс (с нуля)" value={n.index} onChange={index=>patch({index})}/>} {n.operation!=='remove'&&<Expr value={n.value} onChange={value=>patch({value})}/>}</>}{n.kind==='call'&&<><GameSelect label="Вызвать функцию" value={n.functionId} options={[["","Выберите…"],...project.functions.filter(x=>x.id!==f.id).map(x=>[x.id,x.name])]} onChange={functionId=>patch({functionId})}/><JsonValue label="Аргументы" value={n.args||{}} onChange={args=>patch({args})}/><GameField label="Результат в (необязательно)"><input value={n.output||''} onChange={e=>patch({output:e.target.value})}/></GameField></>}{n.kind==='command'&&<GameplayCommandFields project={project} command={n.command?.command} value={n.command?.value} onChange={command=>patch({command})}/>}{!['branch','return'].includes(n.kind)&&<GameSelect label="Следующая нода" value={n.next} options={options} onChange={next=>patch({next})}/>}<Button icon="Trash2" onClick={()=>{edit(f=>{f.nodes=f.nodes.filter(x=>x.id!==n.id);for(const x of f.nodes)for(const k of ['next','trueNext','falseNext'])if(x[k]===n.id)x[k]='';if(f.entry===n.id)f.entry=f.nodes[0]?.id||'';});setNodeId('');}}>{tr('Удалить ноду')}</Button></>}
 <details><summary>{tr('Удалить функцию')}</summary><Button icon="Trash2" onClick={()=>{if(project.gameplay.rules.some(r=>r.functionId===f.id)||project.functions.some(x=>x.nodes.some(n=>n.functionId===f.id))||project.events.some(e=>e.groups.some(g=>g.actions.some(a=>a.command==='callFunction'&&a.value?.functionId===f.id)))){setError(tr('Функция используется. Сначала уберите её вызовы.'));return;}onChange(p=>{p.functions=p.functions.filter(x=>x.id!==f.id);});}}>{tr('Удалить функцию')}</Button></details></aside></div>{error&&<p role="alert">{error}</p>}</>}</div>;
}
