import React from 'react';
import {Button} from './StudioParts.jsx';
import {t as tr,useLocale} from './i18n.jsx';
export default function GameplayGuide({project,onSection,onFunction,onEvent,onWidgets,onInput,onStory}){
 useLocale();const g=project.gameplay,hero=project.objects.find(o=>o.id===g.playerId),enemies=Object.values(g.actors).filter(a=>a.team==='enemy');
 return <div className="gameplay-guide"><section className="gameplay-start"><h2>{tr('FPS целиком в браузере')}</h2><p>{tr('На главной выберите «Шутер · FPS, HP и Game Over». Откроется ваша копия: сцена, оружие, противники, события, Blueprint и виджеты доступны для изменения. Кнопка «Игровые механики» в верхней панели возвращает сюда из любого окна.')}</p><p>{tr('Для создания с нуля: «Настройки игры» → режим «От первого лица» → «Подготовить игровую сцену». Затем создайте противника и добавьте победу кнопками ниже. «Запуск» проверяет игру; «Стоп» возвращает к редактированию.')}</p><Button icon="Gamepad2" onClick={()=>onSection('controller')}>{tr('Открыть настройки FPS')}</Button></section>
 <ol className="gameplay-guide-steps">
  <li><h3>{tr('Персонаж и камера')}</h3><p>{tr('Главный герой — обычный объект «Персонаж». Режим «От первого лица» включает камеру на уровне глаз, движение WASD и прицел. Скорость, прыжок и чувствительность меняются в формах.')}</p><small>{tr('Герой: ')}{hero?.name||tr('ещё не выбран')}</small><Button onClick={()=>onSection('controller')}>{tr('Персонаж и управление')}</Button></li>
  <li><h3>{tr('Стрельба')}</h3><p>{tr('В разделе «Оружие» добавьте пистолет. Укажите урон, магазин, запас и перезарядку. «Мгновенное попадание» проверяет луч из прицела; «Летящий снаряд» создаёт снаряд. ЛКМ и R уже подключены режимом FPS.')}</p><small>{g.weapons.map(w=>`${w.name}: ${w.damage} HP, ${w.magazine} / ${w.reserve}`).join(' · ')||tr('Оружие ещё не добавлено')}</small><Button onClick={()=>onSection('weapons')}>{tr('Открыть оружие')}</Button></li>
  <li><h3>{tr('Противники и здоровье')}</h3><p>{tr('Нажмите «Создать противника в сцене»: появится редактируемый персонаж с 50 HP и преследованием героя. В этом же разделе меняются HP и урон. Расположение объектов меняется в сцене; все противники в этом примере атакуют вблизи.')}</p><small>{tr('Противников: ')}{enemies.length} · {tr('HP героя: ')}{g.actors[g.playerId]?.maxHP||0}</small><Button onClick={()=>onSection('actors')}>{tr('Здоровье и противники')}</Button></li>
  <li><h3>{tr('Game Over и победа')}</h3><p>{tr('«Подготовить игровую сцену» создаёт правило «Смерть героя → Game Over». Кнопка «Добавить победу над всеми противниками» создаёт второе правило и концовку. Для своих условий выберите «Добавить правило»: когда сработать, какой объект, какое событие или продолжение истории.')}</p><Button onClick={()=>onSection('rules')}>{tr('Открыть правила')}</Button><Button onClick={onStory}>{tr('Открыть граф истории')}</Button></li>
  <li><h3>{tr('События и Blueprint')}</h3><p>{tr('Событие собирается из групп и действий. Например: игровая команда «Экипировать» и запись названия оружия в переменную. Blueprint-функция собирается из нод «Если», «Записать значение», «Игровая команда» и «Вернуть результат». В шаблоне так сделаны аптечка и начисление очков.')}</p><div className="gameplay-guide-links"><Button icon="Plus" onClick={()=>onEvent()}>{tr('Создать событие')}</Button><Button icon="Plus" onClick={()=>onFunction('')}>{tr('Редактор Blueprint')}</Button></div><div className="gameplay-guide-assets">{project.events.map(e=><Button key={e.id} icon="Layers" onClick={()=>onEvent(e.id)}>{e.name}</Button>)}{project.functions.map(f=><Button key={f.id} icon="Workflow" onClick={()=>onFunction(f.id)}>{f.name}</Button>)}</div></li>
  <li><h3>{tr('HUD, клавиши и экспорт')}</h3><p>{tr('Виджеты показывают здоровье и патроны через привязки к переменным hp, ammo и reserve. Кнопки могут запускать ваши события. В разделе «Ввод» назначьте клавишу действию «Запустить событие». «Файл → Экспортировать игру (HTML)…» скачивает готовую игру.')}</p><div className="gameplay-guide-links"><Button onClick={onWidgets}>{tr('Редактировать HUD и кнопки')}</Button><Button onClick={onInput}>{tr('Настроить клавиши и геймпад')}</Button><Button onClick={()=>onSection('items')}>{tr('Предметы и инвентарь')}</Button></div></li>
 </ol></div>;
}
