import {allBeats,sceneFor} from './studioModel.js';
import {resolvedPosition,isObjectInScene} from './sceneEditing.js';
import {bodyBounds,rayBox,moveBody,clamp} from './gamePhysics.js';
import {callBlueprint} from './blueprintFunctions.js';
const length=v=>Math.hypot(...v),sub=(a,b)=>a.map((v,i)=>v-b[i]);
const finiteVector=v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite);
export class GameSession {
 constructor(host){this.host=host;this.config=host.project.gameplay;this.started=false;this.flights=new Set();this.direction=[0,0,0];}
 async flushTransition(){if(this.pendingTransition){const id=this.pendingTransition;this.pendingTransition=null;await this.host.enter(id,this.host.generation);return true;}return false;}
 get state(){return this.host.snapshot.world.game;}
 get world(){return this.host.snapshot.world;}
 get scene(){return sceneFor(this.host.project,this.host.snapshot.beatId);}
 get objects(){return this.host.project.objects.filter(o=>o.active!==false&&isObjectInScene(o,this.scene));}
 object(id){return this.objects.find(o=>o.id===id);}
 position(id){const o=this.object(id);return o?resolvedPosition(o,this.world,this.scene.kind):null;}
 initialize(){const g=this.config;this.world.game={clock:0,yaw:0,pitch:0,kills:0,actors:Object.fromEntries(Object.entries(g.actors).map(([id,a])=>[id,{hp:a.maxHP,maxHP:a.maxHP,dead:false,nextAttack:0}])),weapons:Object.fromEntries(g.weapons.map(w=>[w.id,{ammo:w.magazine,reserve:w.reserve,nextShot:0,reloadUntil:0}])),weaponId:g.weapons[0]?.id||'',inventory:[],equipment:{},bodies:{},timers:{},rules:{},projectiles:[],tracers:[],message:''};for(const x of g.inventory.starting)this.addItem(x.itemId,x.count||1);for(const id of Object.values(g.inventory.equipment))this.equip(id);this.sync();}
 enter(){this.destination=null;this.route=null;this.pendingPickup=null;this.direction=[0,0,0];for(const r of this.config.rules)if(this.state.rules[r.id])delete this.state.rules[r.id].inside;this.world.playerControl={characterId:this.config.playerId,mode:this.config.controller.mode,speed:this.config.controller.speed,radius:2};this.state.active=true;this.state.preset=this.config.preset;this.state.controller=this.config.controller;if(!this.started){this.started=true;this.trigger('start');}this.sync();}
 sync(){const s=this.state,p=s.actors[this.config.playerId],w=s.weapons[s.weaponId];if(!s)return;const vars=this.host.snapshot.variables;for(const [id,value]of Object.entries({hp:p?.hp??0,maxHp:p?.maxHP??0,ammo:w?.ammo??0,reserve:w?.reserve??0,kills:s.kills,inventory:s.inventory}))if(Object.hasOwn(vars,id))vars[id]=structuredClone(value);}
 error(e){this.state.message=e.message;this.host.snapshot.hint=e.message;this.host.emit();}
 async trigger(type,payload={},ruleId){
  const tasks=[];
  for(const r of this.config.rules.filter(r=>r.enabled!==false&&(!r.sceneId||r.sceneId===this.scene.id)&&r.trigger===type&&(!ruleId||r.id===ruleId)&&(!r.objectId||r.objectId===payload.objectId))){
   const record=this.state.rules[r.id]??={};if(r.once&&record.fired)continue;record.fired=true;
   const generation=this.host.generation,key='rule:'+r.id+':'+(++this.sequence|| (this.sequence=1));this.flights.add(key);this.queues??=new Map();
   const task=(this.queues.get(r.id)||Promise.resolve()).then(async()=>{
    if(generation!==this.host.generation||!this.host.running)return;
    if(r.functionId)await callBlueprint(this.host.project,r.functionId,payload,this.host.snapshot.variables,c=>this.command(c.command||c.type,c.value));
    if(r.eventId)await this.host.binding({id:'input:rule:'+r.id,eventId:r.eventId,join:'FLOW_END',overrides:{},actionOverrides:{}},generation);
    if(generation===this.host.generation){await this.flushTransition();if(r.nextBeatId&&this.host.running)await this.host.enter(r.nextBeatId,generation);}
   }).catch(e=>{if(!['CANCELLED','INSTANCE_STOPPED'].includes(e.message))this.error(e);}).finally(()=>this.flights.delete(key));
   this.queues.set(r.id,task);tasks.push(task);
  }
  await Promise.all(tasks);
 }

 colliders(){const api=this.host.physicsApi?.current;if(api?.sceneId()===this.scene.id&&api.colliders)return api.colliders();return this.objects.filter(o=>o.collision?.enabled&&this.world.visible[o.id]!==false).map(o=>({id:o.id,box:bodyBounds(o,this.position(o.id),this.scene.id)}));}
 raycast(origin,direction,range,exclude=[]){const api=this.host.physicsApi?.current;if(api?.sceneId()===this.scene.id&&api.raycast)return api.raycast(origin,direction,range,exclude);return this.objects.filter(o=>!exclude.includes(o.id)&&this.world.visible[o.id]!==false&&(o.collision?.enabled||this.state.actors[o.id])).map(o=>{const distance=rayBox(origin,direction,bodyBounds(o,this.position(o.id),this.scene.id),range);return distance===null?null:{id:o.id,distance,point:origin.map((v,i)=>v+direction[i]*distance)};}).filter(Boolean).sort((a,b)=>a.distance-b.distance)[0]||null;}
 damage(id,amount){const a=this.state.actors[id];if(!a||a.dead||!Number.isFinite(amount)||amount<0)return false;a.hp=clamp(a.hp-amount,0,a.maxHP);this.trigger('hit',{objectId:id,amount});if(a.hp===0){a.dead=true;this.trigger('death',{objectId:id});if(id!==this.config.playerId){this.state.kills++;this.world.visible[id]=false;const enemies=Object.keys(this.state.actors).filter(k=>this.config.actors[k].team==='enemy');if(enemies.length&&enemies.every(k=>this.state.actors[k].dead))this.trigger('victory');}else{this.world.playerControl=null;this.host.snapshot.hint='Game Over';}}this.sync();return true;}
 heal(id,amount){const a=this.state.actors[id];if(!a||a.dead)return;a.hp=clamp(a.hp+Math.max(0,amount),0,a.maxHP);this.sync();}
 shoot(payload={}){const s=this.state,w=this.config.weapons.find(w=>w.id===s.weaponId),a=s.weapons[s.weaponId];if(!w||s.actors[this.config.playerId]?.dead||!a||a.nextShot>s.clock||a.reloadUntil>s.clock)return false;if(a.ammo<=0){s.message='Нет патронов. Перезарядите оружие.';return false;}const p=this.position(this.config.playerId);if(!p)return false;const origin=finiteVector(payload.origin)?payload.origin:[p[0],p[1]+this.config.controller.eyeHeight,p[2]],direction=finiteVector(payload.direction)?payload.direction:[-Math.sin(s.yaw)*Math.cos(s.pitch),Math.sin(s.pitch),-Math.cos(s.yaw)*Math.cos(s.pitch)],n=length(direction);if(!n)return false;const dir=direction.map(v=>v/n);a.ammo--;a.nextShot=s.clock+w.cooldown;s.pitch=clamp(s.pitch+w.recoil,-1.5,1.5);if(w.mode==='projectile')s.projectiles.push({id:'p'+s.clock,origin:[...origin],position:[...origin],direction:dir,speed:w.projectileSpeed,remaining:w.range,damage:w.damage,owner:this.config.playerId});else{const hit=this.raycast(origin,dir,w.range,[this.config.playerId]);if(hit)this.damage(hit.id,w.damage);s.tracers.push({from:origin,to:hit?.point||origin.map((v,i)=>v+dir[i]*w.range),until:s.clock+.1});}this.sync();this.host.emit();return true;}
 reload(){const s=this.state,w=this.config.weapons.find(w=>w.id===s.weaponId),a=s.weapons[s.weaponId];if(w&&a&&a.reserve>0&&a.ammo<w.magazine&&a.reloadUntil<=s.clock){a.reloadUntil=s.clock+Math.max(.001,w.reloadTime);s.message='Перезарядка…';}}
 addItem(id,count=1){const item=this.config.items.find(i=>i.id===id);if(!item||!Number.isInteger(count)||count<1)throw new Error('Предмет или количество не заданы.');const inv=this.state.inventory,space=inv.filter(x=>x.itemId===id).reduce((sum,x)=>sum+item.stackLimit-x.count,0)+(this.config.inventory.slots-inv.length)*item.stackLimit;if(count>space)throw new Error('В инвентаре нет свободного места.');let remaining=count;for(const slot of inv.filter(x=>x.itemId===id)){const n=Math.min(remaining,item.stackLimit-slot.count);slot.count+=n;remaining-=n;}while(remaining){const n=Math.min(remaining,item.stackLimit);inv.push({itemId:id,count:n});remaining-=n;}this.sync();return true;}
 count(id){return this.state.inventory.filter(x=>x.itemId===id).reduce((sum,x)=>sum+x.count,0);}
 removeItem(id,count=1){if(!Number.isInteger(count)||count<1||this.count(id)<count)throw new Error('Не хватает предметов.');for(const slot of this.state.inventory.filter(x=>x.itemId===id)){const n=Math.min(count,slot.count);slot.count-=n;count-=n;}this.state.inventory=this.state.inventory.filter(x=>x.count);if(!this.count(id))for(const [slot,value]of Object.entries(this.state.equipment))if(value===id)delete this.state.equipment[slot];if(!this.count(id)&&this.config.items.find(i=>i.id===id)?.weaponId===this.state.weaponId)this.state.weaponId=this.config.weapons[0]?.id||'';this.sync();}
 equip(id){const i=this.config.items.find(i=>i.id===id);if(!i||!this.count(id)||!i.slot)throw new Error('Этот предмет нельзя экипировать.');this.state.equipment[i.slot]=id;if(i.weaponId)this.state.weaponId=i.weaponId;this.sync();}
 async useItem(id){if(this.state.actors[this.config.playerId]?.dead)throw new Error('Герой погиб. Начните игру заново.');const key='item:'+id;if(this.flights.has(key))return;this.flights.add(key);const generation=this.host.generation;try{const i=this.config.items.find(i=>i.id===id);if(!i||!this.count(id))throw new Error('Предмет отсутствует.');if(i.consumable)this.removeItem(id);if(i.heal)this.heal(this.config.playerId,i.heal);if(i.useEventId)await this.host.binding({id:'input:item:'+id,eventId:i.useEventId,join:'FLOW_END',overrides:{},actionOverrides:{}},generation);if(generation===this.host.generation)await this.flushTransition();this.host.emit();}finally{this.flights.delete(key);}}
 combine(id){const r=this.config.recipes.find(r=>r.id===id);if(!r)throw new Error('Рецепт отсутствует.');const totals={};for(const x of r.ingredients)totals[x.itemId]=(totals[x.itemId]||0)+x.count;if(Object.entries(totals).some(([id,n])=>this.count(id)<n))throw new Error('Не хватает ингредиентов.');const before=structuredClone({inventory:this.state.inventory,equipment:this.state.equipment});try{for(const [id,n]of Object.entries(totals))this.removeItem(id,n);this.addItem(r.resultId,r.count||1);}catch(e){Object.assign(this.state,before);this.sync();throw e;}}
 async pickup(item,id){const key='pickup:'+id;this.flights.add(key);try{if(item.pickupEventId)await this.host.binding({id:'input:pickup:'+id,eventId:item.pickupEventId,join:'FLOW_END',overrides:{},actionOverrides:{}},this.host.generation);await this.trigger('pickup',{objectId:id,itemId:item.id});}catch(e){if(!['CANCELLED','INSTANCE_STOPPED'].includes(e.message))this.error(e);}finally{this.flights.delete(key);}}
 interact(id){const item=this.config.items.find(i=>i.worldObjectId===id);if(!item||this.world.visible[id]===false)return false;const p=this.position(this.config.playerId),to=this.position(id);if(!p||!to)return false;if(length(sub(p,to))>2.5){if(['point-click','both'].includes(this.config.controller.mode)){const d=sub(to,p);d[1]=0;const dist=length(d);this.setDestination(p.map((v,i)=>v+d[i]*Math.max(0,(dist-1.5)/(dist||1))));this.pendingPickup=id;return true;}this.state.message='Подойдите ближе к предмету.';return false;}try{this.addItem(item.id);this.world.visible[id]=false;this.pickup(item,id);this.host.emit();return true;}catch(e){this.error(e);return false;}}
 command(command,v={}){if(typeof v!=='object'||v===null)v={amount:Number(v)};const id=v.target||this.config.playerId;switch(command){case'goTo':{const beat=allBeats(this.host.project).find(b=>b.id===v.beatId);if(!beat||!['dialogue','gameplay','gate','choice','end','branch','set-variable','merge'].includes(beat.kind))throw new Error('Нода продолжения не найдена.');this.pendingTransition=v.beatId;return;}case'damage':return this.damage(id,Number(v.amount??25));case'heal':return this.heal(id,Number(v.amount??25));case'shoot':return this.shoot(v);case'reload':return this.reload();case'jump':{const b=this.state.bodies[id];if(b?.grounded)b.velocity[1]=this.config.controller.jumpSpeed;return;}case'impulse':{const b=this.state.bodies[id]??={velocity:[0,0,0],grounded:false};if(!finiteVector(v.velocity))throw new Error('Укажите импульс [x, y, z].');if(this.object(id)?.physics?.mode==='dynamic')b.velocity=b.velocity.map((x,i)=>x+v.velocity[i]);else{b.push=(b.push||[0,0,0]).map((x,i)=>x+(i===1?0:v.velocity[i]));b.velocity[1]+=v.velocity[1];}return;}case'addItem':return this.addItem(v.itemId,v.count??1);case'removeItem':return this.removeItem(v.itemId,v.count??1);case'equip':return this.equip(v.itemId);case'useItem':return this.useItem(v.itemId);case'combine':return this.combine(v.recipeId);case'startTimer':{if(!Number.isFinite(v.seconds)||v.seconds<0)throw new Error('Укажите время таймера.');this.state.timers[v.timerId||'timer']={remaining:v.seconds,objectId:v.objectId||'',repeat:!!v.repeat,seconds:v.seconds};return;}case'stopTimer':delete this.state.timers[v.timerId||'timer'];return;case'callFunction':return callBlueprint(this.host.project,v.functionId,v.args||{},this.host.snapshot.variables,c=>this.command(c.command||c.type,c.value));case'save':return this.host.saveGame();case'load':return this.host.loadGame();default:throw new Error('Неизвестная игровая команда: '+command);}}
 setDestination(point){const player=this.object(this.config.playerId),from=this.position(this.config.playerId);if(!player||!from)return;const to=[point[0],from[1],point[2]],api=this.host.physicsApi?.current;try{this.route=api?.sceneId()===this.scene.id?api.planMotion(player,from,to):[from,to];this.routeIndex=1;this.destination=to;this.state.message='';}catch(e){this.error(e);}}
 step(direction,dt){
  if(direction.some(v=>Math.abs(v)>.001)){this.destination=null;this.route=null;this.pendingPickup=null;}
  if(this.destination){const p=this.position(this.config.playerId),target=this.route?.[this.routeIndex]||this.destination,d=sub(target,p);d[1]=0;const distance=length(d);
   if(distance<.12){if(this.route&&this.routeIndex<this.route.length-1)this.routeIndex++;else{this.destination=null;this.route=null;}}
   else{const stride=Math.max(.001,this.config.controller.speed*Math.min(.05,dt));direction=d.map(v=>v/distance*Math.min(1,distance/stride));}
  }
  this.direction=direction;this.tick(dt);
  if(this.pendingPickup){const p=this.position(this.config.playerId),to=this.position(this.pendingPickup);if(p&&to&&length(sub(p,to))<=2.5){const id=this.pendingPickup;this.pendingPickup=null;this.destination=null;this.route=null;this.interact(id);}}
 }

 tick(dt){if(!this.state?.active||this.host.snapshot.paused||!this.host.snapshot.ready||this.host.snapshot.phase!=='PLAYING')return;dt=clamp(Number(dt)||0,0,.05);const s=this.state;s.clock+=dt;const p=this.position(this.config.playerId);if(!p)return;const boxes=this.colliders();for(const o of this.objects){const actor=s.actors[o.id],isPlayer=o.id===this.config.playerId,ai=this.config.actors[o.id]?.ai,dynamic=o.physics?.mode==='dynamic';if((!isPlayer&&!ai&&!dynamic)||actor?.dead)continue;const pos=this.position(o.id),b=s.bodies[o.id]??={velocity:[0,0,0],grounded:false};let direction=isPlayer?this.direction:[0,0,0];if(ai&&s.actors[this.config.playerId]&&!s.actors[this.config.playerId].dead){const diff=sub(p,pos),distance=length(diff);if(distance<ai.detection){if(distance>ai.range)direction=[diff[0]/(distance||1),0,diff[2]/(distance||1)];else if(s.clock>=actor.nextAttack){actor.nextAttack=s.clock+Math.max(.05,ai.interval);const eye=pos.map((v,i)=>v+(i===1?1:0)),target=p.map((v,i)=>v+(i===1?1:0)),d=sub(target,eye),hit=this.raycast(eye,d.map(v=>v/(length(d)||1)),length(d),[o.id]);if(!hit||hit.id===this.config.playerId)this.damage(this.config.playerId,ai.damage);}}}const speed=isPlayer?this.config.controller.speed:ai?.speed||0;if(isPlayer&&this.config.controller.mode==='none')direction=[0,0,0];if(!dynamic){b.velocity[0]=direction[0]*speed+(b.push?.[0]||0);b.velocity[2]=direction[2]*speed+(b.push?.[2]||0);if(b.push)b.push=b.push.map(v=>v*Math.exp(-dt*6));}b.velocity[1]-=(o.physics?.gravity??this.config.controller.gravity)*dt;const result=moveBody(o,pos,b.velocity.map(v=>v*dt),boxes,this.scene.id,{velocity:b.velocity,bounce:dynamic?o.physics?.bounce||0:0});const bounds=bodyBounds(o,result.position,this.scene.id),ground=this.scene.navMesh?.center?.[1]||0;if(bounds.min[1]<ground){result.position[1]+=ground-bounds.min[1];result.velocity[1]=0;result.grounded=true;}const nav=this.scene.navMesh;if(isPlayer&&nav?.enabled){result.position[0]=clamp(result.position[0],nav.center[0]-nav.size[0]/2+.3,nav.center[0]+nav.size[0]/2-.3);result.position[2]=clamp(result.position[2],nav.center[2]-nav.size[1]/2+.3,nav.center[2]+nav.size[1]/2-.3);}this.world.positions[o.id]=result.position;b.velocity=result.velocity;b.grounded=result.grounded;for(const id of result.contacts)if(!b.contacts?.includes(id))this.trigger('collision',{objectId:id,actorId:o.id});b.contacts=result.contacts;}
 for(const projectile of s.projectiles){const d=Math.min(projectile.remaining,projectile.speed*dt),hit=this.raycast(projectile.position,projectile.direction,d,[projectile.owner]);if(hit){this.damage(hit.id,projectile.damage);projectile.remaining=0;}else{projectile.position=projectile.position.map((v,i)=>v+projectile.direction[i]*d);projectile.remaining-=d;}}s.projectiles=s.projectiles.filter(p=>p.remaining>0);s.tracers=s.tracers.filter(t=>t.until>s.clock);
 for(const [id,a]of Object.entries(s.weapons))if(a.reloadUntil&&a.reloadUntil<=s.clock){const w=this.config.weapons.find(w=>w.id===id),n=Math.min(w.magazine-a.ammo,a.reserve);a.ammo+=n;a.reserve-=n;a.reloadUntil=0;s.message='';}
 for(const [id,t]of Object.entries(s.timers)){t.remaining-=dt;if(t.remaining<=0){if(t.repeat)t.remaining=Math.max(.001,t.seconds);else delete s.timers[id];this.trigger('timer',{objectId:t.objectId,timerId:id});}}
 const current=this.position(this.config.playerId);for(const r of this.config.rules.filter(r=>r.enabled!==false&&(!r.sceneId||r.sceneId===this.scene.id))){const record=s.rules[r.id]??={};if(['enter','exit'].includes(r.trigger)){const zonePosition=r.objectId?this.position(r.objectId):current;if(!zonePosition)continue;const inside=r.center.every((v,i)=>Math.abs(zonePosition[i]-v)<=r.size[i]/2);if(inside!==!!record.inside){record.inside=inside;if(inside&&r.trigger==='enter'||!inside&&r.trigger==='exit')this.fireRule(r);} }else if(['timer','tick'].includes(r.trigger)&&(!record.fired||r.repeat||r.trigger==='tick')){record.elapsed=(record.elapsed||0)+dt;if(record.elapsed>=Math.max(.001,r.seconds)){record.elapsed=0;this.fireRule(r);}}}this.sync();this.host.emit();}
 fireRule(rule){return this.trigger(rule.trigger,{objectId:rule.objectId},rule.id);}
 look(value,device){if(this.config.preset!=='fps'&&this.config.preset!=='thirdPerson')return;const speed=device==='pointer'?this.config.controller.sensitivity:.03;this.state.yaw-=value[0]*speed;this.state.pitch=clamp(this.state.pitch-value[1]*speed,-1.5,1.5);}
}
