import {variableType,runtimeVariableType,VARIABLE_TYPES} from './variableModel.js';
import React from 'react';
import {Handle,Position} from '@xyflow/react';
import {Icon} from './StudioParts.jsx';
import {ValueField} from './ChoiceInspector.jsx';
import {VALUE_TYPES,variableName,ANSWER_VARIABLE,typedValue} from './choiceModel.js';
import {compareSymbols,isPureNode,MATH_OPERATIONS} from './logicModel.js';
export default function LogicNode({data,selected}){
 const n=data.beat,patch=values=>data.onLogicChange(n.id,values),pure=isPureNode(n);
 const type=variableType(data.project,n.variable)||n.valueType||'string',typeLabel=VARIABLE_TYPES.find(([id])=>id===type)?.[1].split(' · ')[0]||'String';
 const input=(port,label,value,type='number')=><div className="logic-row" key={port}><Handle className="data-pin" type="target" position={Position.Left} id={port} title={label+' · вход значения'}/><span>{label}</span>{n.inputs?.[port]?<small>Подключено</small>:<ValueField label={label+' '+n.id} type={type} value={value} onChange={v=>patch({[port]:v})}/>}</div>;
 if(n.kind==='variable')return <article className={'story-moment variable-get type-'+type+(selected?' selected':'')} onDoubleClick={()=>data.onInspectVariable?.(n.variable)}><header className="moment-grab"><i className="variable-type-dot"/><strong>{variableName(n.variable)||'Переменная не найдена'}</strong></header><p className="variable-caption">GET · {typeLabel}</p><Handle className="data-pin" type="source" position={Position.Right} id="value" title="Значение · выход"/>{data.issue&&<div className="moment-issue">{data.issue.title}</div>}</article>;
 if(n.kind==='set-variable')return <article className={'story-moment logic-node variable-set type-'+type+(selected?' selected':'')} onDoubleClick={()=>data.onInspectVariable?.(n.variable)}><header className="moment-grab"><Icon name="Database" size={16}/><strong>SET · {variableName(n.variable)}</strong></header><div className="logic-body nodrag"><div className="logic-row"><Handle type="target" position={Position.Left} id="in" title="Выполнить Set"/><span>Выполнить</span><Handle type="source" position={Position.Right} id="next" title="Продолжить после Set"/></div>{input('value',typeLabel,n.value,runtimeVariableType(data.project,n.variable)||n.valueType)}</div><div className="logic-row logic-output"><span>Значение</span><Handle className="data-pin" type="source" position={Position.Right} id="value" title="Значение после Set"/></div>{data.issue&&<div className="moment-issue">{data.issue.title}</div>}</article>;
 return <article className={'story-moment logic-node'+(n.kind==='branch'?' logic-if':'')+(selected?' selected':'')}>
 <header className="moment-grab"><Icon name={n.kind==='branch'?'GitFork':n.kind==='variable'?'Database':'Binary'} size={16}/><strong>{n.kind==='variable'?'Переменная':n.kind==='literal'?'Значение':n.kind==='math'?MATH_OPERATIONS[n.operator]?.label:n.kind==='convert'?'Конвертация':n.kind==='not'?'НЕ':n.kind==='compare'?compareSymbols[n.operator]:n.kind==='and'?'И':n.kind==='or'?'ИЛИ':n.kind==='set-variable'?'Задать переменную':'If · Если'}</strong>{n.kind==='branch'&&<span className="logic-if-badge">ВЕТВЛЕНИЕ</span>}</header>
 <div className="logic-body nodrag" onClick={e=>e.stopPropagation()}>
 {n.kind==='literal'&&<><label>Тип<select value={n.valueType||'string'} onChange={e=>patch({valueType:e.target.value,value:''})}>{VALUE_TYPES.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><ValueField label={'Значение '+n.id} type={n.valueType} value={n.value} onChange={value=>patch({value})}/></>}
 {n.kind==='compare'&&<><label>Оператор<select aria-label={'Оператор '+n.id} value={n.operator} onChange={e=>patch({operator:e.target.value,...(!['eq','ne'].includes(e.target.value)?{valueType:'number',a:typedValue(n.a,'number'),b:typedValue(n.b,'number')}:{})})}>{Object.entries(compareSymbols).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>Тип<select aria-label={'Тип сравнения '+n.id} value={n.valueType||'number'} onChange={e=>patch({valueType:e.target.value,a:'',b:''})}>{VALUE_TYPES.filter(([v])=>['eq','ne'].includes(n.operator)||v==='number').map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{input('a','A',n.a,n.valueType)}{input('b','B',n.b,n.valueType)}</>}
 {n.kind==='math'&&<><label>Операция<select aria-label={'Математическая операция '+n.id} value={n.operator||'add'} onChange={e=>patch({operator:e.target.value})}>{Object.entries(MATH_OPERATIONS).map(([id,op])=><option key={id} value={id}>{op.label}</option>)}</select></label>{input('a','A',n.a??0,'number')}{MATH_OPERATIONS[n.operator]?.arity===2&&input('b','B',n.b??0,'number')}</>}
 {n.kind==='convert'&&<><label>Преобразовать в<select aria-label={'Тип конвертации '+n.id} value={n.valueType||'string'} onChange={e=>patch({valueType:e.target.value})}>{VALUE_TYPES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{input('value','Значение',n.value??'',n.inputType||'string')}<small>Да / нет: true / false, да / нет, 1 / 0. Число: корректная запись числа.</small></>}
 {n.kind==='not'&&input('a','Условие',n.a??false,'boolean')}
 {['and','or'].includes(n.kind)&&<>{input('a','A',false,'boolean')}{input('b','B',false,'boolean')}</>}
 {n.kind==='branch'&&<><div className="logic-row"><Handle type="target" position={Position.Left} id="in"/><span>Выполнить</span></div>{input('condition','Условие',n.condition??false,'boolean')}<p>Да → первый путь. Нет → второй.</p></>}
 </div>
 {pure?<div className="logic-row logic-output"><span>{n.kind==='variable'?variableName(n.variable)||'Значение':['compare','and','or','not'].includes(n.kind)?'Результат · Да / нет':n.kind==='math'?'Результат · Число':n.kind==='convert'?'Результат · '+typeLabel:'Значение'}</span><Handle className="data-pin" type="source" position={Position.Right} id="value" title="Значение · выход"/></div>:<footer>{data.ports.map(port=><div className={"moment-route"+(n.kind==='branch'?" logic-if-route logic-if-"+port.id:"")} key={port.id}><span>{n.kind==='branch'&&<Icon name={port.id==='true'?'Check':'X'} size={16}/>}<strong>{port.label}</strong></span><Handle type="source" position={Position.Right} id={port.id}/></div>)}</footer>}
 {data.issue&&<div className="moment-issue">{data.issue.title}</div>}
 </article>;
}
