import {t as tr, useLocale, message} from './i18n.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {Button,Icon} from './StudioParts.jsx';
import WidgetRenderer from './WidgetRenderer.jsx';
import {uid} from './model.js';
import {createWidget,createWidgetElement,ELEMENT_TYPES,WIDGET_KINDS,WIDGET_ROLES,MENU_ACTIONS,widgetRects,rectTransform,reanchor,removeWidget,removeWidgetElement,scopeWidgetCss} from './widgetModel.js';

const presets=[['↖','Слева сверху',[0,0]],['↑','Сверху',[.5,0]],['↗','Справа сверху',[1,0]],['←','Слева',[0,.5]],['·','По центру',[.5,.5]],['→','Справа',[1,.5]],['↙','Слева снизу',[0,1]],['↓','Снизу',[.5,1]],['↘','Справа снизу',[1,1]]];
function NumberField({label,value,onChange,min,max,step=1}){
 useLocale();return <label>{tr(label)}<input type="number" min={min} max={max} step={step} value={Math.round(value*1000)/1000} onChange={e=>{if(e.target.value==='')return;const number=Number(e.target.value);if(Number.isFinite(number))onChange(Math.min(max??Infinity,Math.max(min??-Infinity,number)));}}/></label>;}
function Slider({label,value,onChange,min=0,max=100,step=1}){
 useLocale();return <label>{tr(label)}<div className="widget-slider"><input aria-label={tr(label)} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><input aria-label={tr(label)+tr(" — число")} type="number" min={min} max={max} step={step} value={value} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(Math.min(max,Math.max(min,n)));}}/></div></label>;}
export default function WidgetWorkspace({project,onChange,request,running,onStop,onPreview,beat}){
 useLocale();
 const [widgetId,setWidgetId]=useState(request?.id||project.ui.dialogue),[elementId,setElementId]=useState(null),[frame,setFrame]=useState([1280,720]),[snap,setSnap]=useState(true),[draft,setDraft]=useState(null),[error,setError]=useState(''),[fit,setFit]=useState(1);
 const viewport=useRef(),drag=useRef();
 useEffect(()=>{if(request?.id){setWidgetId(request.id);setElementId(null);setDraft(null);}},[request]);
 const saved=project.widgets.find(w=>w.id===widgetId)||project.widgets[0],widget=draft||saved,element=widget.elements.find(e=>e.id===elementId),rects=widgetRects(widget,frame[0],frame[1]),logicalRects=widgetRects(widget),referenceScale=Math.min(frame[0]/widget.referenceSize[0],frame[1]/widget.referenceSize[1]);
 useEffect(()=>{const node=viewport.current;if(!node)return;const observer=new ResizeObserver(()=>setFit(Math.max(.05,Math.min((node.clientWidth-30)/frame[0],(node.clientHeight-30)/frame[1]))));observer.observe(node);return()=>observer.disconnect();},[frame]);
 useEffect(()=>{setDraft(null);drag.current=null;},[widgetId,running]);
 const edit=fn=>{if(running)return;setError('');onChange(p=>fn(p.widgets.find(w=>w.id===saved.id),p));};
 const patch=values=>edit(w=>Object.assign(w.elements.find(e=>e.id===elementId),values));
 const layout=values=>patch({layout:{...element.layout,...values}}),style=(key,value)=>patch({style:{...element.style,[key]:value}});
 const parentSize=element?.parentId?logicalRects[element.parentId]:{width:widget.referenceSize[0],height:widget.referenceSize[1]};
 const changeAnchor=(min,max,pivot=element.layout.pivot)=>patch({layout:reanchor(element.layout,parentSize,min,max,pivot)});
 const add=type=>{const id=uid('ui-element');edit(w=>w.elements.push(createWidgetElement(id,type,{parentId:element?.type==='panel'?element.id:null})));setElementId(id);};
 const create=(copy=false)=>{const id=uid('widget');onChange(p=>{const w=copy?{...structuredClone(saved),id,name:saved.name+' · копия'}:createWidget(id,saved.kind,'Новый '+WIDGET_KINDS[saved.kind].toLowerCase());p.widgets.push(w);});setWidgetId(id);setElementId(null);};
 const begin=(event,item,resize=false)=>{if(running||event.button!==0)return;event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);setElementId(item.id);drag.current={id:item.id,x:event.clientX,y:event.clientY,resize,widget:structuredClone(saved),layout:{...item.layout},scale:fit*referenceScale};};
 const move=event=>{const d=drag.current;if(!d)return;const step=snap?8:1,quantize=v=>Math.round(v/step)*step,dx=(event.clientX-d.x)/d.scale,dy=(event.clientY-d.y)/d.scale,next=structuredClone(d.widget),target=next.elements.find(e=>e.id===d.id);
  if(d.resize){const bounds=widgetRects(d.widget)[d.id],dw=Math.max(20-bounds.width,quantize(dx)),dh=Math.max(20-bounds.height,quantize(dy));Object.assign(target.layout,{width:d.layout.width+dw,height:d.layout.height+dh,x:d.layout.x+dw*d.layout.pivot[0],y:d.layout.y+dh*d.layout.pivot[1]});}
  else Object.assign(target.layout,{x:d.layout.x+quantize(dx),y:d.layout.y+quantize(dy)});
  setDraft(next);
 };
 const finish=event=>{const d=drag.current;if(!d)return;drag.current=null;if(draft){const final=draft.elements.find(e=>e.id===d.id).layout;onChange(p=>Object.assign(p.widgets.find(w=>w.id===d.widget.id).elements.find(e=>e.id===d.id).layout,final));}setDraft(null);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);};
 const cancel=()=>{drag.current=null;setDraft(null);};
 const sample={speaker:beat?.speaker||'Алиса',text:beat?.text||tr('Так будет выглядеть диалог в вашей игре. Перетащите окно или настройте его анкеры.'),title:project.title,status:tr('Нажмите, чтобы продолжить'),choices:beat?.kind==='choice'?beat.choices:[{id:'sample-a',label:tr('Остаться и поговорить')},{id:'sample-b',label:tr('Продолжить путь')}],ready:true,canAdvance:true,paused:true};
 const cssError=scopeWidgetCss(widget.css,'.widget').error;
 return <div className="widget-workspace">
  <header><strong><Icon name="PanelsTopLeft" size={16}/>{tr("Редактор виджетов")}</strong><select aria-label={tr("Виджет для редактирования")} value={saved.id} onChange={e=>{setWidgetId(e.target.value);setElementId(null);}}>{project.widgets.map(w=><option key={w.id} value={w.id}>{w.name} · {tr(WIDGET_KINDS[w.kind])}</option>)}</select><Button icon="Copy" disabled={running} onClick={()=>create(true)}>{tr("Копия")}</Button><Button icon="Plus" disabled={running} onClick={()=>create()}>{tr("Создать")}</Button><Button icon="Play" disabled={running} onClick={()=>onPreview(saved)}>{tr("Проверить в игре")}</Button></header>
  {running&&<div className="camera-running">{tr("Остановите игру для редактирования.")}<Button icon="Square" onClick={onStop}>{tr("Остановить")}</Button></div>}
  {error&&<p className="widget-css-error" role="alert">{message(error)}</p>}
  <div className="widget-body"><aside className="widget-library"><h3>{tr("Интерфейс проекта")}</h3>{Object.entries(WIDGET_KINDS).map(([kind,label])=><label key={kind}>{tr(label)}<select aria-label={tr("Стандартный виджет: ")+tr(label)} disabled={running} value={project.ui[kind]} onChange={e=>onChange(p=>{p.ui[kind]=e.target.value;})}>{project.widgets.filter(w=>w.kind===kind).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>)}<h3>{tr("Элементы")}</h3>{widget.elements.map(e=><button key={e.id} aria-pressed={e.id===elementId} className={e.id===elementId?'active':''} style={{paddingLeft:e.parentId?22:8}} onClick={()=>setElementId(e.id)}><Icon name={e.type==='panel'?'Square':e.type==='image'?'Image':e.type==='button'?'MousePointer2':'Type'} size={13}/>{e.name}{!e.visible&&<Icon name="EyeOff" size={12}/>}</button>)}<select aria-label={tr("Добавить элемент виджета")} disabled={running} value="" onChange={e=>add(e.target.value)}><option value="">{tr("＋ Добавить элемент…")}</option>{Object.entries(ELEMENT_TYPES).map(([id,label])=><option key={id} value={id}>{tr(label)}</option>)}</select><small>{tr("Новый элемент добавляется внутрь выбранной панели. Стрелки перемещают выбранный элемент; Shift — шаг 10.")}</small></aside>
  <main className="widget-canvas-area"><div className="widget-canvas-toolbar"><select aria-label={tr("Разрешение предпросмотра виджета")} value={frame.join('x')} onChange={e=>setFrame(e.target.value.split('x').map(Number))}>{[[1280,720],[1920,1080],[1024,768],[720,1280],[2560,1080]].map(s=><option key={s.join('x')}>{s.join('x')}</option>)}</select><label><input type="checkbox" checked={snap} onChange={e=>setSnap(e.target.checked)}/> {tr("Привязка 8 px")}</label><span className="micro">{Math.round(fit*100)}%</span></div><div className="widget-canvas-viewport" ref={viewport}><div className="widget-canvas" style={{width:frame[0],height:frame[1],transform:`translate(${-frame[0]*fit/2}px,${-frame[1]*fit/2}px) scale(${fit})`}}><div className="widget-grid"/><WidgetRenderer widget={widget} context={sample} editing width={frame[0]} height={frame[1]}/>
   {widget.elements.map(e=>{const r=rects[e.id];return r&&<div key={e.id} role="button" tabIndex={0} aria-label={tr("Выбрать и переместить: ")+e.name} className={'widget-hit'+(elementId===e.id?' selected':'')+(!e.visible?' hidden':'')} style={{left:r.x,top:r.y,width:r.width,height:r.height}} onClick={()=>setElementId(e.id)} onPointerDown={event=>begin(event,e)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} onLostPointerCapture={cancel} onKeyDown={event=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[event.key];if(!delta||running)return;event.preventDefault();const step=event.shiftKey?10:1;edit(w=>{const l=w.elements.find(x=>x.id===e.id).layout;l.x+=delta[0]*step;l.y+=delta[1]*step;});}}>{elementId===e.id&&<span role="button" aria-label={tr("Изменить размер: ")+e.name} className="widget-resize" onPointerDown={event=>begin(event,e,true)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel}/>}</div>;})}
   {element&&(()=>{const p=element.parentId?rects[element.parentId]:{x:0,y:0,width:frame[0],height:frame[1]},l=element.layout;return <><div className="widget-anchor-line" style={{left:p.x+p.width*l.anchorMin[0],top:p.y+p.height*l.anchorMin[1],width:p.width*(l.anchorMax[0]-l.anchorMin[0]),height:p.height*(l.anchorMax[1]-l.anchorMin[1])}}/>{[l.anchorMin,l.anchorMax].map((a,i)=><span className="widget-anchor-point" key={i} style={{left:p.x+p.width*a[0],top:p.y+p.height*a[1]}}/>)}</>;})()}
  </div></div></main>
  <aside className="widget-properties"><fieldset disabled={running} style={{border:0,padding:0,margin:0,minWidth:0}}><h3>{tr("Виджет")}</h3><label>{tr("Название")}<input value={saved.name} onChange={e=>edit(w=>{w.name=e.target.value;})}/></label><label>{tr("Тип")}<select value={saved.kind} onChange={e=>{const kind=e.target.value;edit((w,p)=>{w.kind=kind;for(const k of Object.keys(WIDGET_KINDS)){if(!p.widgets.some(v=>v.kind===k))p.widgets.push(createWidget(uid('widget'),k));if(!p.widgets.some(v=>v.id===p.ui[k]&&v.kind===k))p.ui[k]=p.widgets.find(v=>v.kind===k).id;}});}}>{Object.entries(WIDGET_KINDS).map(([id,label])=><option key={id} value={id}>{tr(label)}</option>)}</select></label><div className="widget-number-row">{['Ширина холста','Высота холста'].map((label,i)=><NumberField key={label} label={tr(label)} min={100} max={7680} value={widget.referenceSize[i]} onChange={v=>edit(w=>{w.referenceSize[i]=v;})}/>)}</div>
  {element?<><h3>{tr("Элемент")}</h3><label>{tr("Название")}<input value={element.name} onChange={e=>patch({name:e.target.value})}/></label><label><span><input type="checkbox" checked={element.visible} onChange={e=>patch({visible:e.target.checked})}/> {tr("Видимый")}</span></label><label>{tr("Родитель")}<select value={element.parentId||''} onChange={e=>{const newParent=e.target.value||null;const r=logicalRects[element.id],p=newParent?logicalRects[newParent]:{x:0,y:0,width:widget.referenceSize[0],height:widget.referenceSize[1]};patch({parentId:newParent,layout:rectTransform({anchorMin:[0,0],anchorMax:[0,0],pivot:[0,0],x:r.x-p.x,y:r.y-p.y,width:r.width,height:r.height})});}}><option value="">{tr("Холст")}</option>{widget.elements.filter(e=>{if(e.type!=='panel'||e.id===element.id)return false;let p=e,seen=new Set();while(p&&!seen.has(p.id)){if(p.parentId===element.id)return false;seen.add(p.id);p=widget.elements.find(v=>v.id===p.parentId);}return true;}).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>
  <details open><summary>{tr("Положение и анкеры")}</summary><div className="widget-presets">{presets.map(([symbol,label,a])=><button key={label} title={tr(label)} aria-label={tr(label)} className={element.layout.anchorMin.every((v,i)=>v===a[i])&&element.layout.anchorMax.every((v,i)=>v===a[i])?'active':''} onClick={()=>changeAnchor(a,a,a)}>{symbol}</button>)}</div><div className="widget-presets"><button onClick={()=>changeAnchor([0,element.layout.anchorMin[1]],[1,element.layout.anchorMax[1]])}>{tr("По ширине")}</button><button onClick={()=>changeAnchor([element.layout.anchorMin[0],0],[element.layout.anchorMax[0],1])}>{tr("По высоте")}</button><button onClick={()=>changeAnchor([0,0],[1,1])}>{tr("Заполнить")}</button></div><small>{tr("Смена анкеров сохраняет положение. Растяжение задаёт отступы через X/Y и добавку к размеру.")}</small><div className="widget-number-row">{[['x','X'],['y','Y'],['width','Ширина / Δ'],['height','Высота / Δ']].map(([key,label])=><NumberField key={key} label={tr(label)} value={element.layout[key]} onChange={v=>layout({[key]:v})}/>)}</div>{['anchorMin','anchorMax','pivot'].map(key=><div className="widget-number-row" key={key}>{[0,1].map(i=><NumberField key={i} label={({anchorMin:'Anchor Min',anchorMax:'Anchor Max',pivot:'Pivot'}[key])+' '+(i?'Y':'X')} min={0} max={1} step={.05} value={element.layout[key][i]} onChange={v=>{const array=[...element.layout[key]];array[i]=key==='anchorMin'?Math.min(v,element.layout.anchorMax[i]):key==='anchorMax'?Math.max(v,element.layout.anchorMin[i]):v;changeAnchor(key==='anchorMin'?array:element.layout.anchorMin,key==='anchorMax'?array:element.layout.anchorMax,key==='pivot'?array:element.layout.pivot);}}/>)}</div>)}</details>
  <details open><summary>{tr("Содержимое и действия")}</summary><label>{tr("Привязка к игре")}<select value={element.role} onChange={e=>patch({role:e.target.value})}>{Object.entries(WIDGET_ROLES).map(([id,label])=><option key={id} value={id}>{tr(label)}</option>)}</select></label>{element.type!=='panel'&&<label>{tr("Текст / подпись")}<textarea rows={2} value={element.text||''} onChange={e=>patch({text:e.target.value})}/></label>}{element.type==='button'&&<label>{tr("Действие")}<select value={element.action} onChange={e=>patch({action:e.target.value})}>{Object.entries(MENU_ACTIONS).map(([id,label])=><option key={id} value={id}>{tr(label)}</option>)}</select></label>}{element.type==='image'&&<><label>{tr("URL изображения")}<input value={element.src||''} onChange={e=>patch({src:e.target.value})}/></label><label>{tr("Загрузить изображение")}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={async e=>{const file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024){setError('Выберите изображение до 2 МБ.');return;}const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});patch({src});}}/></label></>}</details>
  <details open><summary>{tr("Оформление")}</summary>{[['background','Фон'],['color','Цвет текста'],['borderColor','Цвет рамки']].map(([key,label])=><label key={key}>{tr(label)}<div className="widget-slider"><input aria-label={tr(label)} type="color" value={/^#[\da-f]{6}$/i.test(element.style[key])?element.style[key]:'#211c29'} onChange={e=>style(key,e.target.value)}/><input aria-label={tr(label)+tr(" — CSS-цвет")} value={element.style[key]||'transparent'} onChange={e=>style(key,e.target.value)}/></div></label>)}{[['fontSize','Размер текста',72],['borderRadius','Скругление',100],['borderWidth','Рамка',12],['padding','Отступы',80],['gap','Расстояние ответов',40],['opacity','Непрозрачность',1]].map(([key,label,max])=><Slider key={key} label={tr(label)} value={element.style[key]??(key==='opacity'?1:0)} max={max} step={key==='opacity'?.01:1} onChange={v=>style(key,v)}/>)}<label>{tr("Шрифт")}<input value={element.style.fontFamily||'system-ui'} onChange={e=>style('fontFamily',e.target.value)}/></label><label>{tr("Начертание")}<select value={element.style.fontWeight||400} onChange={e=>style('fontWeight',Number(e.target.value))}>{[400,500,600,700].map(w=><option key={w}>{w}</option>)}</select></label><label>{tr("Выравнивание")}<select value={element.style.textAlign||'left'} onChange={e=>style('textAlign',e.target.value)}><option value="left">{tr("Слева")}</option><option value="center">{tr("По центру")}</option><option value="right">{tr("Справа")}</option></select></label></details>
  <div className="button-row"><Button icon="ArrowUp" disabled={widget.elements.indexOf(element)===0} onClick={()=>edit(w=>{const i=w.elements.findIndex(e=>e.id===elementId);[w.elements[i-1],w.elements[i]]=[w.elements[i],w.elements[i-1]];})}>{tr("Назад")}</Button><Button icon="ArrowDown" disabled={widget.elements.indexOf(element)===widget.elements.length-1} onClick={()=>edit(w=>{const i=w.elements.findIndex(e=>e.id===elementId);[w.elements[i+1],w.elements[i]]=[w.elements[i],w.elements[i+1]];})}>{tr("Вперёд")}</Button></div><Button icon="Trash2" onClick={()=>{edit(w=>removeWidgetElement(w,element.id));setElementId(null);}}>{tr("Удалить элемент и детей")}</Button></>:<p className="widget-empty">{tr("Выберите элемент на холсте или в списке слева.")}</p>}
  <details><summary>{tr("CSS виджета")}</summary><small>{tr("CSS применяется после параметров инспектора. :widget — холст; .widget-element — элементы; [data-role=\"dialogueText\"] — текст реплики.")}</small><label>CSS<textarea aria-label={tr("CSS виджета")} rows={9} spellCheck={false} value={widget.css} placeholder={'[data-role="dialogueText"] {\n  color: #f6d7e8;\n}'} onChange={e=>edit(w=>{w.css=e.target.value;})}/></label>{cssError&&<p className="widget-css-error" role="alert">{message(cssError)}</p>}<small>{tr("ID выбранного элемента: ")}{element?.id||'—'}</small></details><Button icon="Trash2" disabled={project.widgets.filter(w=>w.kind===saved.kind).length<2} onClick={()=>{try{onChange(p=>removeWidget(p,saved.id));setElementId(null);}catch(cause){setError(cause.message);}}}>{tr("Удалить виджет")}</Button></fieldset></aside></div><p className="widget-save-note">{tr("Изменения сохраняются с проектом · Ctrl+Z — отмена · бирюзовые метки — анкеры · розовая рамка — выбранный элемент")}</p>
 </div>;
}
