import React,{useState,useEffect,useMemo,useRef} from 'react';
import * as Icons from 'lucide-react';
import Scene from './Scene.jsx';
import FailureLab from './FailureLab.jsx';
import {createProject,uid,TYPES,makeAction,allBeats,resolvedActions,targetName,validate,fixIssue,available,applyBeat,nextNode,routeTo} from './model.js';

const Icon=({name,size=16,...props})=>{const C=Icons[name]||Icons.Sparkles;return <C size={size} strokeWidth={1.65} {...props}/>;};
const Button=({children,icon,className='',...props})=><button className={`btn ${className}`} {...props}>{icon&&<Icon name={icon}/>} {children}</button>;
const Field=({label,children,hint})=><label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
const Select=({value,onChange,options,...props})=><select value={value??''} onChange={e=>onChange(e.target.value)} {...props}>{options.map(o=><option key={typeof o==='string'?o:o[0]} value={typeof o==='string'?o:o[0]}>{typeof o==='string'?o:o[1]}</option>)}</select>;
const Tag=({children,tone='purple',icon})=><span className={`tag ${tone}`}>{icon&&<Icon name={icon} size={12}/>} {children}</span>;
const HOOKS=[['BEFORE','До реплики'],['ON_START','С репликой'],['AFTER','После реплики']];
const JOINS=[['NONE','Сразу, не ждать'],['STARTED','Когда событие запущено'],['FLOW_END','Когда выполнены шаги'],['EVENT_END','Когда событие завершено']];
const KEY='sacura-ui-project-v1';
function loadProject(){try{const p=JSON.parse(localStorage.getItem(KEY));if(p?.version===1&&p.events?.length&&p.chapters?.length)return p;}catch{}return createProject();}

export default function App(){
 const [project,setProject]=useState(loadProject),[workspace,setWorkspace]=useState('scene'),[view,setView]=useState('story'),[chapter,setChapter]=useState('letter-scene'),[expanded,setExpanded]=useState(['letter-scene']),[focus,setFocus]=useState('l3'),[selection,setSelection]=useState({type:'binding',beat:'l3',index:0}),[leftTab,setLeftTab]=useState('story'),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[libraryTab,setLibraryTab]=useState('События'),[editingEvent,setEditingEvent]=useState('window'),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[checksOpen,setChecksOpen]=useState(false),[run,setRun]=useState(null),[route,setRoute]=useState({}),[history,setHistory]=useState([]),[ambientOpen,setAmbientOpen]=useState(true),[inspectorOpen,setInspectorOpen]=useState(true),[saved,setSaved]=useState(true),[objectFilter,setObjectFilter]=useState('all'),[showBranches,setShowBranches]=useState(false);
 const undo=useRef([]),fileInput=useRef(),lastAdvance=useRef(0),previewProject=useRef(null),projectRef=useRef(project);projectRef.current=project;
 const beats=allBeats(project),current=run?allBeats(previewProject.current).find(b=>b.id===run.beatId):(beats.find(b=>b.id===focus)||beats[0]),issues=useMemo(()=>validate(project),[project]),activeChapter=project.chapters.find(c=>c.id===chapter)||project.chapters[0],state=run||{...project.scene,positions:{},variables:project.variables};
 const selectedBeat=beats.find(b=>b.id===selection.beat)||current;
 const binding=selection.type==='binding'?selectedBeat.bindings[selection.index]:null;
 const event=binding?project.events.find(e=>e.id===binding.eventId):project.events.find(e=>e.id===editingEvent);
 const selectedObject=project.objects.find(o=>o.id===selection.id);
 const change=(fn)=>{setProject(p=>{undo.current.push(structuredClone(p));if(undo.current.length>30)undo.current.shift();const copy=structuredClone(p);const result=typeof fn==='function'?fn(copy):fn;return result?.version===1?result:copy;});setSaved(false);};
 const notify=text=>{setToast(text);};
 useEffect(()=>{const t=setTimeout(()=>{try{localStorage.setItem(KEY,JSON.stringify(project));setSaved(true);}catch{notify('Браузер не смог сохранить проект. Скачайте JSON.');}},450);return()=>clearTimeout(t);},[project]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{if(window.innerWidth<821)setInspectorOpen(false);const t=setTimeout(()=>document.getElementById('beat-l3')?.scrollIntoView({block:'start'}),250);return()=>clearTimeout(t);},[]);
 useEffect(()=>{if(!run?.duck)return;const t=setTimeout(()=>setRun(r=>r?{...r,duck:false}:r),2400);return()=>clearTimeout(t);},[run?.duck,run?.beatId]);
 useEffect(()=>{if(!run||current.kind!=='gate'||run.variables[current.signal])return;const t=setTimeout(()=>setRun(r=>r?{...r,hint:true}:r),Math.max(1,Number(current.timeout)||45)*1000);return()=>clearTimeout(t);},[run?.beatId,run?.variables[current?.signal]]);
 useEffect(()=>{const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'inspect_sacura_scenario',title:'Проверить сценарий Sacura',description:'Read the local UI prototype scene counts and computed diagnostics without modifying it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');const p=projectRef.current,b=allBeats(p);return {title:p.title,blocks:b.length,choices:b.filter(n=>n.kind==='choice').length,eventTemplates:p.events.length,diagnostics:validate(p)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 useEffect(()=>{const handler=e=>{if(e.key==='Escape'){setModal(null);setChecksOpen(false);setSearchOpen(false);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA'].includes(e.target.tagName)){e.preventDefault();restoreUndo();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 const restoreUndo=()=>{const p=undo.current.pop();if(p){setProject(p);notify('Изменение отменено');}};
 const reveal=(beatId,select=true)=>{const c=project.chapters.find(c=>c.beats.some(b=>b.id===beatId));if(!c)return;const target=c.beats.find(b=>b.id===beatId);if(target?.branch){const additions={};let branch=target.branch;while(branch){const owner=beats.find(b=>b.choices?.some(ch=>ch.id===branch));if(!owner)break;additions[owner.id]=branch;branch=owner.branch;}setRoute(r=>({...r,...additions}));}setChapter(c.id);setExpanded(v=>[...new Set([...v,c.id])]);setFocus(beatId);if(select)setSelection({type:'beat',beat:beatId});setWorkspace('scene');setTimeout(()=>document.getElementById(`beat-${beatId}`)?.scrollIntoView({behavior:'smooth',block:'center'}),50);};
 const editBeat=fn=>change(p=>{fn(allBeats(p).find(b=>b.id===selectedBeat.id));});
 const editBinding=(key,value)=>editBeat(b=>{b.bindings[selection.index][key]=value;});
 const override=(key,value)=>editBeat(b=>{b.bindings[selection.index].overrides[key]=value;});
 const editObject=(key,value)=>change(p=>{p.objects.find(o=>o.id===selection.id)[key]=value;});
 const editEvent=(key,value)=>change(p=>{p.events.find(e=>e.id===editingEvent)[key]=value;});
 const editAction=(groupId,actionId,key,value)=>change(p=>{p.events.find(e=>e.id===editingEvent).groups.find(g=>g.id===groupId).actions.find(a=>a.id===actionId)[key]=value;});
 const addBinding=(eventId,beatId=focus)=>{change(p=>{const b=allBeats(p).find(b=>b.id===beatId),ev=p.events.find(e=>e.id===eventId);b.bindings.push({id:uid('binding'),eventId,hook:'ON_START',join:ev.retention==='AUTO_CLOSE_ON_FLOW_END'?'EVENT_END':'FLOW_END',overrides:{}});});setSelection({type:'binding',beat:beatId,index:(beats.find(b=>b.id===beatId)?.bindings.length||0)});setWorkspace('scene');setModal(null);reveal(beatId,false);notify('Событие добавлено к реплике');};
 const startPreview=()=>{if(run){stopPreview();return;}if(issues.length){setChecksOpen(true);notify('Перед запуском исправьте ошибки сценария');return;}previewProject.current=structuredClone(project);setHistory([]);setRoute(routeTo(project,current.id));const initial=applyBeat(previewProject.current,current,{...project.scene,positions:{},variables:structuredClone(project.variables),instances:[],duck:false});setRun({...initial,beatId:current.id});setWorkspace('scene');notify('Предпросмотр с выбранной реплики');};
 const stopPreview=()=>{setRun(null);setHistory([]);notify('Предпросмотр остановлен. Состояние сцены восстановлено.');};
 const nextBeat=(choiceId)=>{
  if(!run)return;if(Date.now()-lastAdvance.current<250)return;lastAdvance.current=Date.now();
  if(current.kind==='gate'&&!run.variables[current.signal]){notify(`Сценарий ждёт взаимодействия: ${targetName(project,current.signal)}`);return;}
  if(current.kind==='choice'&&!choiceId)return;
  const nextRoute={...route};if(choiceId){const c=current.choices.find(c=>c.id===choiceId);if(!c||!available(c,run.variables))return;nextRoute[current.id]=choiceId;setRoute(nextRoute);}
  const next=nextNode(previewProject.current,current.id,nextRoute,choiceId);
  if(!next){stopPreview();notify('Глава завершена. Фоновые события закрыты.');return;}
  if(history.filter(h=>h.focus===next.id).length>=5){notify('Остановлено: цикл переходов посетил один блок 5 раз. Проверьте цели ответов.');return;}
  setHistory(h=>[...h,{focus:current.id,run:structuredClone(run),route:{...route}}]);const after=applyBeat(previewProject.current,current,run,['AFTER']);setRun({...applyBeat(previewProject.current,next,{...after,duck:false}),beatId:next.id});reveal(next.id);
 };
 const backPreview=()=>{const previous=history.at(-1);if(!previous)return;setRun(previous.run);setRoute(previous.route);reveal(previous.focus);setHistory(h=>h.slice(0,-1));};
 const interact=(id)=>{if(!run){setSelection({type:'object',id});return;}const obj=previewProject.current.objects.find(o=>o.id===id);if(!obj?.active||obj.type!=='Активный меш'){notify('Объект недоступен для взаимодействия');return;}setRun(r=>({...r,variables:{...r.variables,[id]:true}}));notify(`${obj.name} · условие выполнено`);};
 const moveBinding=(id)=>{if(id===selectedBeat.id)return;const idx=beats.find(b=>b.id===id).bindings.length;change(p=>{const source=allBeats(p).find(b=>b.id===selectedBeat.id);const [moved]=source.bindings.splice(selection.index,1);allBeats(p).find(b=>b.id===id).bindings.push(moved);});setSelection({type:'binding',beat:id,index:idx});reveal(id,false);notify('Событие перенесено к другой реплике');};
 const fix=(issue)=>{change(p=>fixIssue(p,issue));notify('Настройки исправлены. Проверка обновлена.');};
 const exportProject=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='sacura-ui-project.json';a.click();URL.revokeObjectURL(url);notify('Проект сохранён в JSON');};
 const importProject=async e=>{try{const p=JSON.parse(await e.target.files[0].text());if(p.version!==1||!Array.isArray(p.events)||!Array.isArray(p.chapters)||!Array.isArray(p.objects)||!p.chapters[0]?.beats?.length)throw Error();validate(p);change(p);setRun(null);setChapter(p.chapters[0].id);setExpanded([p.chapters[0].id]);setFocus(p.chapters[0].beats[0].id);setSelection({type:'beat',beat:p.chapters[0].beats[0].id});notify('Проект загружен');}catch{notify('Не удалось прочитать проект: нужен JSON этого макета');}e.target.value='';};
 const objectOptions=[...project.objects.map(o=>[o.id,o.name]),['world','Мир'],['audio','Музыка'],['camera','Главная камера'],['trust','Доверие']];
 const titleCount=beats.filter(b=>b.kind==='dialogue').length;

 return <div className={`studio ${inspectorOpen?'':'no-inspector'}`}>
  <header className="topbar">
   <div className="brand"><img src="/favicon.svg"/><strong>sacura<span>studio</span></strong><span className="prototype-label">UI CONCEPT</span></div>
   <button className="mobile-library" title="Переключить сценарий и библиотеку" onClick={()=>{setWorkspace(w=>w==='scene'?'library':'scene');setInspectorOpen(false);}}><Icon name={workspace==='scene'?'Shapes':'Clapperboard'}/></button><div className="project-title"><Icon name="FolderOpen" size={15}/>{project.title}<Icon name="ChevronDown" size={13}/></div>
   <div className="top-actions"><span className="save-state"><Icon name={saved?'CloudCheck':'CloudUpload'} size={15}/>{saved?'Сохранено локально':'Сохраняем…'}</span><button title="Отменить изменение · Ctrl+Z" onClick={restoreUndo}><Icon name="Undo2"/></button><button title="Поиск · Ctrl+K" onClick={()=>setSearchOpen(true)}><Icon name="Search"/></button><Button icon={run?'Square':'Play'} className={`primary ${run?'running':''}`} onClick={startPreview}>{run?'Остановить':'Протестировать'}</Button></div>
  </header>
  <aside className="sidebar">
   <div className="project-card"><div className="project-art"><Icon name="House" size={23}/></div><div><strong>{project.title}</strong><small>Визуальная новелла · 3D</small></div></div>
   <nav className="main-nav"><button className={workspace==='scene'?'active':''} onClick={()=>setWorkspace('scene')}><Icon name="Clapperboard"/>Сценарий<span>01</span></button><button className={workspace==='library'?'active':''} onClick={()=>{setWorkspace('library');setSelection({type:'event'});}}><Icon name="Shapes"/>Библиотека</button></nav>
   <div className="sidebar-divider"/>
   <div className="sidebar-tabs"><button className={leftTab==='story'?'active':''} onClick={()=>setLeftTab('story')}>Структура</button><button className={leftTab==='objects'?'active':''} onClick={()=>setLeftTab('objects')}>Объекты <span>{project.objects.length}</span></button></div>
   <div className="sidebar-scroll">
   {leftTab==='story'?<><div className="tree-heading"><Icon name="ChevronDown" size={13}/><Icon name="BookOpen" size={15}/><strong>Глава 1. Возвращение</strong></div><div className="subscene-label"><Icon name="ChevronDown" size={13}/><Icon name="Layers" size={15}/><span>Вечер в гостиной</span><Tag tone="gray">Сабсцена</Tag></div>
    <div className="chapter-tree">{project.chapters.map((c,i)=>{const errors=issues.filter(x=>c.beats.some(b=>b.id===x.beatId)).length;return <button className={`chapter-link ${chapter===c.id?'active':''}`} key={c.id} onClick={()=>{setChapter(c.id);setExpanded(v=>[...new Set([...v,c.id])]);setWorkspace('scene');setFocus(c.beats[0].id);setSelection({type:'beat',beat:c.beats[0].id});setTimeout(()=>document.getElementById(`chapter-${c.id}`)?.scrollIntoView({behavior:'smooth',block:'start'}),40);}}><span className="chapter-order">{String(i+1).padStart(2,'0')}</span><span>{c.name}<small>{c.beats.length} блоков{c.beats.some(b=>b.kind==='choice')?' · развилка':''}</small></span>{errors>0&&<span className="error-dot">{errors}</span>}</button>;})}</div>
    <button className="add-episode" onClick={()=>setModal({type:'chapter'})}><Icon name="Plus" size={14}/>Добавить эпизод</button>
   </>:<><div className="object-heading">В этой сабсцене<button title="Добавить объект" onClick={()=>setModal({type:'object'})}><Icon name="Plus"/></button></div>{project.objects.map(o=><button className={`object-item ${selection.id===o.id?'active':''}`} key={o.id} onClick={()=>{setSelection({type:'object',id:o.id});setInspectorOpen(true);}}><span className="object-avatar" style={{color:o.color,background:o.color+'18'}}><Icon name={o.type==='Персонаж'?'UserRound':'Box'}/></span><span>{o.name}<small>{o.type}</small></span><Icon name={o.active?'Eye':'EyeOff'} size={13}/></button>)}<button className="add-episode" onClick={()=>setModal({type:'object'})}><Icon name="Plus" size={14}/>Добавить объект</button></>}
   </div>
   <div className="sidebar-bottom"><button onClick={()=>setChecksOpen(true)} className={issues.length?'has-errors':''}><Icon name={issues.length?'CircleAlert':'ShieldCheck'}/><span>Проверка проекта</span><b>{issues.length||'✓'}</b></button><button onClick={()=>setModal({type:'help'})}><Icon name="CircleHelp"/><span>Как здесь всё устроено</span><Icon name="ArrowUpRight" size={13}/></button><div className="file-actions"><button onClick={exportProject}><Icon name="Download" size={14}/>Экспорт</button><button onClick={()=>fileInput.current.click()}><Icon name="Upload" size={14}/>Импорт</button></div><input type="file" hidden ref={fileInput} accept=".json" onChange={importProject}/></div>
  </aside>
  <main className="main">
  {workspace==='scene'?<>
   <div className="workspace-heading"><div className="breadcrumb">Глава 1 <Icon name="ChevronRight" size={12}/><span>Вечер в гостиной</span><Tag tone="gray">Сабсцена</Tag></div><div className="workspace-tools"><button title="Показать свойства" onClick={()=>setInspectorOpen(!inspectorOpen)}><Icon name="PanelRight"/></button><button title="Настройки проекта" onClick={()=>setModal({type:'project'})}><Icon name="Settings2"/></button></div></div>
   <section className={`viewport ${run?'playing':''}`}>
    <Scene objects={run?previewProject.current.objects:project.objects} state={state} selected={selection.type==='object'?selection.id:'alice'} onSelect={id=>{setSelection({type:'object',id});if(run){interact(id);}else setInspectorOpen(true);}} onLetter={()=>{}}/>
    <div className="viewport-top"><span className="viewport-label"><span className="live-dot"/> {run?'ПРЕДПРОСМОТР':'СЦЕНА'} <span className="separator">/</span> Гостиная</span><div className="scene-switches"><button onClick={()=>run?setRun(r=>({...r,time:r.time==='Ночь'?'Закат':'Ночь'})):change(p=>{p.scene.time=p.scene.time==='Ночь'?'Закат':'Ночь';})}><Icon name={state.time==='Ночь'?'Moon':'Sun'} size={13}/>{state.time}</button><button onClick={()=>run?setRun(r=>({...r,weather:r.weather==='Ясно'?'Дождь':'Ясно'})):change(p=>{p.scene.weather=p.scene.weather==='Ясно'?'Дождь':'Ясно';})}><Icon name="CloudRain" size={13}/>{state.weather}</button></div></div>
    <div className="scene-bottom"><button className="camera-select" onClick={()=>run?setRun(r=>({...r,camera:r.camera==='Общий план'?'Крупный план':'Общий план'})):change(p=>{p.scene.camera=p.scene.camera==='Общий план'?'Крупный план':'Общий план';})}><Icon name="Video" size={14}/>{state.camera}<Icon name="ChevronDown" size={12}/></button><span>Примитивы · вращайте сцену мышью</span><div className="axis"><i>Y</i><b>Z</b><em>X</em></div></div>
    {run&&<div className="play-dialogue"><div className="play-speaker">{current.speaker}</div><p>{current.text}</p>{run.hint&&current.kind==='gate'&&!run.variables[current.signal]&&<p className="play-hint">Подсказка: {targetName(project,current.signal)} доступен через кнопку взаимодействия ниже или прямо в сцене.</p>}{current.kind==='choice'?<div className="play-choices">{current.choices.map(c=><button disabled={!available(c,run.variables)} onClick={()=>nextBeat(c.id)} key={c.id}>{c.label}{!available(c,run.variables)&&<Icon name="LockKeyhole" size={12}/>}</button>)}</div>:<div className="play-controls"><button onClick={backPreview} disabled={!history.length}><Icon name="SkipBack" size={14}/></button>{current.kind==='gate'&&!run.variables[current.signal]?<Button icon="MousePointer2" onClick={()=>interact(current.signal)}>{previewProject.current.objects.find(o=>o.id===current.signal)?.interaction||'Взаимодействовать'}</Button>:<Button onClick={()=>nextBeat()} icon="ArrowRight">{current.kind==='end'?'Завершить':'Продолжить'}</Button>}<span>{current.kind==='gate'&&!run.variables[current.signal]?'Ждём действие игрока':`Доверие: ${run.variables.trust}`}</span></div>}</div>}
   </section>
   <div className="timeline-head"><div><Icon name="ListTree" size={20}/><h1>Сценарий</h1><span className="count-pill">{beats.length} блоков</span></div><div className="view-switch"><button className={view==='story'?'active':''} onClick={()=>setView('story')}><Icon name="AlignLeft" size={14}/>Лента</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}><Icon name="Workflow" size={14}/>Карта веток</button></div><Button icon="Plus" className="subtle" onClick={()=>setModal({type:'beat'})}>Добавить</Button></div>
   <div className="timeline-toolbar"><div className="context-path"><Icon name="Route" size={13}/><span>Все ветки</span><Icon name="ChevronRight" size={12}/><b>{activeChapter.name}</b></div><div><select aria-label="Фильтр по персонажу" value={objectFilter} onChange={e=>setObjectFilter(e.target.value)}><option value="all">Все персонажи</option>{project.objects.filter(o=>o.type==='Персонаж').map(o=><option key={o.id} value={o.name}>{o.name}</option>)}</select><button title="Свернуть все эпизоды" onClick={()=>setExpanded([])}><Icon name="ChevronsDownUp" size={15}/></button></div></div>
   {view==='story'?<div className="story-scroll">
    {project.chapters.map((c,ci)=><section className={`chapter ${expanded.includes(c.id)?'expanded':''}`} id={`chapter-${c.id}`} key={c.id}>
     <button className="chapter-header" onClick={()=>{setExpanded(v=>v.includes(c.id)?v.filter(x=>x!==c.id):[...v,c.id]);setChapter(c.id);}}><Icon name={expanded.includes(c.id)?'ChevronDown':'ChevronRight'} size={15}/><span className="chapter-number">{String(ci+1).padStart(2,'0')}</span><strong>{c.name}</strong><small>{c.beats.length} блоков · {c.beats.reduce((a,b)=>a+b.bindings.length,0)} событий</small>{issues.some(x=>c.beats.some(b=>b.id===x.beatId))&&<Icon name="CircleAlert" size={14} className="error-text"/>}</button>
     {expanded.includes(c.id)&&<div className="chapter-content">{c.beats.filter(b=>(showBranches||!b.branch||Object.values(route).includes(b.branch))&&(objectFilter==='all'||b.speaker===objectFilter||b.kind!=='dialogue')).map((b,bi)=>{
      const ownIssues=issues.filter(i=>i.beatId===b.id),isFocus=focus===b.id;
      return <article id={`beat-${b.id}`} className={`beat ${b.kind} ${isFocus?'focused':''} ${b.branch?'branch-beat':''}`} key={b.id}>
       <button className="beat-index" onClick={()=>{setFocus(b.id);setSelection({type:'beat',beat:b.id});}} title="Выбрать блок">{b.kind==='choice'?<Icon name="GitBranch" size={15}/>:b.kind==='gate'?<Icon name="MousePointer2" size={15}/>:b.kind==='merge'?<Icon name="GitMerge" size={15}/>:String(c.beats.findIndex(n=>n.id===b.id)+1).padStart(2,'0')}</button>
       <div className="beat-body" onClick={()=>{setFocus(b.id);setSelection({type:'beat',beat:b.id});}} tabIndex={0} role="button" onKeyDown={e=>{if(e.key==='Enter'){setFocus(b.id);setSelection({type:'beat',beat:b.id});setInspectorOpen(true);}}}>
        {b.kind==='choice'?<><div className="beat-type"><Icon name="GitBranch" size={14}/>ВЫБОР ИГРОКА<span>{b.choices.length} варианта</span></div><h3>{b.text}</h3><div className="choice-cards">{b.choices.map((ch,i)=><button key={ch.id} className={`${!available(ch,state.variables)?'locked':''} ${route[b.id]===ch.id?'chosen':''}`} onClick={e=>{e.stopPropagation();if(run&&current.id===b.id){nextBeat(ch.id);}else{setRoute(r=>({...r,[b.id]:ch.id}));reveal(ch.next||b.id);}}}><span className="choice-letter">{String.fromCharCode(65+i)}</span><strong>{ch.label}</strong><small>{ch.condition==='always'?<><Icon name="Check" size={12}/>Всегда доступно</>:<><Icon name="LockKeyhole" size={12}/>{ch.condition==='trust'?`Доверие ≥ ${ch.threshold}`:'Письмо найдено'}</>}</small><span className="choice-destination">{c.beats.filter(x=>x.branch===ch.id).length} реплики <Icon name="ArrowDownRight" size={12}/></span></button>)}</div><div className="branch-note"><Icon name="GitMerge" size={13}/>Ветки снова встретятся в общей точке<button onClick={e=>{e.stopPropagation();setShowBranches(v=>!v);}}>{showBranches?'Свернуть ветки':'Раскрыть все ветки'}</button></div></>
        :b.kind==='gate'?<><div className="beat-type"><Icon name="MousePointer2" size={14}/>ЖДЁМ ИГРОКА<Tag tone="amber">Время не ограничено</Tag></div><h3>{b.text}</h3><p>Продолжить, когда игрок нажмёт <b>{targetName(project,b.signal)}</b>. Музыка и мир продолжают работать.</p><div className="gate-footer"><Tag tone="amber" icon="MousePointerClick">{targetName(project,b.signal)} → {project.objects.find(o=>o.id===b.signal)?.interaction||'Осмотреть'}</Tag><span>Через {b.timeout} с — подсказка</span></div></>
        :b.kind==='merge'?<div className="merge-line"><Icon name="GitMerge" size={14}/><span>Ветки сходятся</span><p>{b.text}</p></div>
        :<><div className="speaker-line"><span className={`speaker ${b.speaker==='Алиса'?'alice':b.speaker==='Боб'?'bob':''}`}>{b.speaker}</span>{b.branch&&<Tag tone="gray">{beats.flatMap(x=>x.choices||[]).find(c=>c.id===b.branch)?.label||b.branch}</Tag>}{b.kind==='end'&&<Tag tone="green">Конец сабсцены</Tag>}<button className="beat-more" title="Настроить реплику" onClick={e=>{e.stopPropagation();setSelection({type:'beat',beat:b.id});setFocus(b.id);setInspectorOpen(true);}}><Icon name="Ellipsis" size={16}/></button></div><p className="dialogue-text">{b.text}</p></>}
        {!!b.bindings.length&&<div className="beat-events"><span className="events-mode" title="Порядок событий у реплики"><Icon name={b.mode==='PARALLEL'?'Columns2':'ListOrdered'} size={12}/>{b.mode==='PARALLEL'?'Вместе':'По очереди'}</span>{b.bindings.map((binding,index)=>{const ev=project.events.find(e=>e.id===binding.eventId);const type=ev?.groups[0]?.actions[0]?.type||'move';return <button key={binding.id} className={`event-chip ${['music','pause','resume','duck','stop','sound'].includes(type)?'audio':['weather','time'].includes(type)?'world':''} ${selection.type==='binding'&&selection.beat===b.id&&selection.index===index?'selected':''} ${ownIssues.some(i=>i.eventId===binding.eventId)?'invalid':''}`} onClick={e=>{e.stopPropagation();setFocus(b.id);setSelection({type:'binding',beat:b.id,index});setInspectorOpen(true);}}><Icon name={TYPES[type]?.icon} size={13}/>{ev?.name||'Событие удалено'}{binding.hook!=='ON_START'&&<small>{binding.hook==='BEFORE'?'до':'после'}</small>}{ownIssues.some(i=>i.eventId===binding.eventId)&&<Icon name="CircleAlert" size={12}/>}</button>;})}<button className="add-chip" title="Добавить событие к реплике" onClick={e=>{e.stopPropagation();setFocus(b.id);setModal({type:'attach',beatId:b.id});}}><Icon name="Plus" size={13}/></button></div>}
        {ownIssues.length>0&&<button className="inline-issue" onClick={e=>{e.stopPropagation();setChecksOpen(true);}}><Icon name="CircleAlert" size={13}/>{ownIssues[0].title}<Icon name="ArrowUpRight" size={12}/></button>}
       </div>
      </article>;
     })}<button className="insert-block" onClick={()=>{setChapter(c.id);setModal({type:'beat',chapterId:c.id});}}><Icon name="Plus" size={13}/>Добавить блок в эпизод</button></div>}
    </section>)}
   </div>:<div className="map-scroll"><div className="map-intro"><div><h2>Одна история. Несколько путей.</h2><p>{project.chapters.length} эпизодов · {beats.filter(b=>b.kind==='choice').length} развилок · общие точки схождения</p></div><Tag tone="gray">Нажмите на блок, чтобы перейти к нему</Tag></div><div className="story-map">{project.chapters.map((c,i)=><div className="map-chapter" key={c.id}><button className="map-node" onClick={()=>{setView('story');reveal(c.beats[0].id);}}><span>{String(i+1).padStart(2,'0')}</span><strong>{c.name}</strong><small>{c.beats.length} блоков</small>{issues.some(x=>c.beats.some(b=>b.id===x.beatId))&&<Icon name="CircleAlert" size={14} className="error-text"/>}</button>{c.beats.filter(b=>b.kind==='choice').map(b=><div className={`map-branch ${b.branch?'nested':''}`} key={b.id}>{b.branch&&<div className="map-condition">Только в ветке «{beats.flatMap(n=>n.choices||[]).find(c=>c.id===b.branch)?.label||b.branch}»</div>}<div className="map-choice-title"><Icon name="GitBranch" size={14}/>{b.text}</div><div className="map-options">{b.choices.map(ch=><button key={ch.id} onClick={()=>{setView('story');reveal(ch.next||b.id);}}><span>{ch.label}</span><small>{ch.condition==='always'?'Всегда':ch.condition==='trust'?`Доверие ≥ ${ch.threshold}`:'Письмо найдено'}</small><b>{c.beats.filter(x=>x.branch===ch.id).length} реплики</b></button>)}</div><div className="map-merge"><Icon name="GitMerge" size={14}/>Общий путь</div></div>)}{c.beats.filter(b=>b.kind==='gate').map(b=><button className="map-gate" key={b.id} onClick={()=>{setView('story');reveal(b.id);}}><Icon name="MousePointer2"/>Осмотреть письмо<span>Мир продолжает жить</span></button>)}</div>)}</div></div>}
   <section className={`ambient ${ambientOpen?'':'collapsed'}`}><button className="ambient-heading" onClick={()=>setAmbientOpen(!ambientOpen)}><Icon name="Waves" size={14}/><strong>Продолжается в фоне</strong><span>Не задерживает диалог</span><Icon name={ambientOpen?'ChevronDown':'ChevronUp'} size={13}/></button>{ambientOpen&&<div className="ambient-tracks"><button className="ambient-track music-track" onClick={()=>{setEditingEvent('bgm');setSelection({type:'event'});setWorkspace('library');}}><Icon name="Music2" size={15}/><span>Музыка</span><div className={`waveform ${state.musicState==='playing'?'playing':''}`}>{Array.from({length:64},(_,i)=><i key={i} style={{height:`${5+(Math.sin(i*2.9)+1)*7}px`}}/>)}</div><small>{state.musicState==='paused'?'Пауза':state.musicState==='stopped'?'Остановлена':state.duck?'Приглушена −12 dB':'After the rain'}</small><Tag tone="green">До остановки</Tag></button><div className="ambient-bottom"><span><Icon name="CloudRain" size={13}/>{state.weather}<i>·</i><Icon name="Sun" size={13}/>{state.time}</span><span><Icon name="AudioLines" size={13}/>Голос → музыка <b>{state.duck?'−12 dB':'Сайдчейн'}</b></span><button onClick={()=>setModal({type:'runtime'})}><Icon name="Activity" size={13}/>Состояние выполнения</button></div></div>}</section>
  </>:<>
   <div className="library-header"><div><div className="eyebrow">ПЕРЕИСПОЛЬЗУЕМЫЕ ЭЛЕМЕНТЫ</div><h1>Библиотека</h1><p>Создайте один раз. Используйте в любой сцене.</p></div><Button className="primary" icon="Plus" onClick={()=>setModal({type:libraryTab==='Объекты'?'object':'event',category:libraryTab})}>Создать</Button></div>
   <div className="library-tabs">{['События','Группы','Действия','Объекты'].map(t=><button className={libraryTab===t?'active':''} key={t} onClick={()=>setLibraryTab(t)}>{t}<span>{t==='Объекты'?project.objects.length:t==='События'?project.events.length:t==='Группы'?project.events.reduce((n,e)=>n+e.groups.length,0):Object.keys(TYPES).length}</span></button>)}</div>
   <div className="library-scroll">
   {libraryTab==='Объекты'?<div className="asset-grid">{project.objects.map(o=><button className="asset-card" key={o.id} onClick={()=>{setSelection({type:'object',id:o.id});setInspectorOpen(true);}}><span className="asset-icon" style={{color:o.color}}><Icon name={o.type==='Персонаж'?'UserRound':'Box'} size={26}/></span><h3>{o.name}</h3><p>{o.type}</p><Tag tone="gray">В гостиной</Tag></button>)}</div>
   :libraryTab==='Действия'?<><div className="library-explanation"><Icon name="Zap"/><p>Действие — одна команда. Выберите тип, затем настройте объект и результат.</p></div><div className="action-type-grid">{Object.entries(TYPES).map(([type,data])=><button key={type} onClick={()=>setModal({type:'event',actionType:type,category:'Действия'})}><Icon name={data.icon} size={22}/><strong>{data.label}</strong><small>{data.completion==='CONTINUOUS'?'Работает до остановки':data.completion==='INSTANT'?'Меняет состояние':'Имеет завершение'}</small><Icon name="Plus" size={15}/></button>)}</div></>
   :<><div className="event-library-strip">{project.events.map(e=><button className={editingEvent===e.id?'selected':''} key={e.id} onClick={()=>{setEditingEvent(e.id);setSelection({type:'event'});}}><Icon name={TYPES[e.groups[0]?.actions[0]?.type]?.icon}/><span>{e.name}<small>{e.groups.length} {libraryTab==='Группы'?'последовательных шагов':'шагов'} · {e.groups.reduce((n,g)=>n+g.actions.length,0)} действий</small></span></button>)}</div>
    {event&&<div className="event-builder"><div className="event-builder-heading"><div><Tag icon="Shapes">{libraryTab==='Группы'?'Группы действий':'Шаблон события'}</Tag><input aria-label="Название события" className="title-input" value={event.name} onChange={e=>editEvent('name',e.target.value)}/><p>Шаги идут по очереди. Действия внутри шага начинаются вместе.</p></div><Button className="subtle" icon="Plus" onClick={()=>addBinding(event.id)}>В сцену</Button></div>
     {event.groups.map((g,gi)=><div className="group-wrap" key={g.id}>{gi>0&&<div className="group-connector"><Icon name="ArrowDown" size={15}/>После выполнения шага и остановки его временных эффектов</div>}<section className="group-card"><div className="group-heading"><span className="step-number">{String(gi+1).padStart(2,'0')}</span><input aria-label="Название группы" value={g.name} onChange={e=>change(p=>{p.events.find(ev=>ev.id===editingEvent).groups.find(gr=>gr.id===g.id).name=e.target.value;})}/><Tag tone="gray" icon="Columns2">Действия вместе</Tag><button title="Переместить шаг выше" disabled={!gi} onClick={()=>change(p=>{const gs=p.events.find(ev=>ev.id===editingEvent).groups;[gs[gi],gs[gi-1]]=[gs[gi-1],gs[gi]];})}><Icon name="ArrowUp" size={14}/></button></div>
      {g.actions.map(a=><div className={`action-row ${selection.actionId===a.id?'selected':''}`} key={a.id} onClick={()=>setSelection({type:'action',actionId:a.id,groupId:g.id})}><span className="action-icon"><Icon name={TYPES[a.type]?.icon} size={20}/></span><div><strong>{TYPES[a.type]?.label}</strong><span>{targetName(project,a.target)} <Icon name="ArrowRight" size={12}/> {a.value}</span></div><small>{a.wait==='COMPLETED'?'Ждать завершения':a.wait==='STARTED'?'Ждать запуска':'Не ждать'}</small><button title="Удалить действие" disabled={g.actions.length===1} onClick={e=>{e.stopPropagation();change(p=>{const gr=p.events.find(ev=>ev.id===editingEvent).groups.find(gr=>gr.id===g.id);gr.actions=gr.actions.filter(x=>x.id!==a.id);});}}><Icon name="Trash2" size={14}/></button><Icon name="ChevronRight" size={14}/></div>)}
      <button className="add-action" onClick={()=>setModal({type:'action',groupId:g.id})}><Icon name="Plus" size={14}/>Добавить действие в этот шаг</button><div className="barrier-note"><Icon name="CheckCheck" size={13}/>Дождаться выбранных результатов → остановить временные эффекты → следующий шаг</div>
     </section></div>)}<button className="add-step" onClick={()=>change(p=>{p.events.find(ev=>ev.id===editingEvent).groups.push({id:uid('group'),name:'Следующий шаг',actions:[makeAction('pose','alice','улыбка')]});})}><Icon name="Plus"/>Добавить следующий шаг</button><Button className="reuse-step" icon="Library" onClick={()=>setModal({type:'group'})}>Добавить готовую группу</Button>
     {issues.filter(i=>i.eventId===event.id).map(i=><div className="builder-issue" key={i.id}><Icon name="CircleAlert"/><div><b>{i.title}</b><p>{i.detail}</p></div><Button onClick={()=>fix(i)}>Исправить</Button></div>)}
    </div>}
   </>}
   </div>
  </>}
  </main>

  {inspectorOpen&&<aside className="inspector"><div className="inspector-heading"><strong>{selection.type==='binding'?'Событие в сцене':selection.type==='object'?'Объект':selection.type==='action'?'Действие':selection.type==='event'?'Шаблон события':'Блок сценария'}</strong><button title="Закрыть свойства" onClick={()=>setInspectorOpen(false)}><Icon name="PanelRightClose" size={15}/></button></div><div className="inspector-scroll">
  {selection.type==='binding'&&binding&&event?<>
   <div className="inspector-title"><span className="large-icon"><Icon name={TYPES[event.groups[0]?.actions[0]?.type]?.icon} size={23}/></span><h2>{event.name}</h2><p>Размещение в этой сабсцене</p></div>
   <button className="template-source" onClick={()=>{setEditingEvent(event.id);setWorkspace('library');setSelection({type:'event'});}}><Icon name="Shapes"/><span>Из шаблона <b>{event.name}</b></span><Icon name="ArrowUpRight" size={14}/></button>
   <section className="property-section"><h4>ЗАПУСК</h4><Field label="На какой реплике"><Select value={selectedBeat.id} onChange={moveBinding} options={beats.map(b=>[b.id,b.text.slice(0,40)])}/></Field><Field label="Когда запустить"><Select value={binding.hook} onChange={v=>editBinding('hook',v)} options={HOOKS}/></Field><Field label="События в одной фазе реплики"><div className="segmented"><button className={selectedBeat.mode==='SEQUENTIAL'?'active':''} onClick={()=>editBeat(b=>b.mode='SEQUENTIAL')}><Icon name="ListOrdered" size={13}/>По очереди</button><button className={selectedBeat.mode==='PARALLEL'?'active':''} onClick={()=>editBeat(b=>b.mode='PARALLEL')}><Icon name="Columns2" size={13}/>Вместе</button></div></Field><Field label="Когда продолжить сценарий"><Select value={binding.join} onChange={v=>editBinding('join',v)} options={JOINS}/></Field><Field label="Условие запуска"><Select value={binding.condition||'always'} onChange={v=>editBinding('condition',v)} options={[["always","Всегда"],["letter","Если найдено письмо"],["trust","Если доверие ≥ 3"]]}/></Field><div className="human-note"><Icon name="CornerDownRight" size={14}/><span>{binding.join==='NONE'?'Следующее событие начнётся сразу. Действия могут пересечься.':binding.join==='FLOW_END'?'Дождёмся шагов постановки. Фон может продолжать работать.':binding.join==='STARTED'?'Продолжим после подтверждения запуска.':`Следующая реплика дождётся события «${event.name}».`}</span></div></section>
   {event.groups[0]?.actions[0]&&(()=>{const a={...event.groups[0].actions[0],...binding.overrides};return <section className="property-section"><h4>ПАРАМЕТРЫ ПЕРВОГО ДЕЙСТВИЯ <span>{Object.keys(binding.overrides).length>0&&`${Object.keys(binding.overrides).length} изм.`}</span></h4><Field label={a.type==='move'?'Кто двигается':'Объект действия'}><Select value={a.target} onChange={v=>override('target',v)} options={objectOptions}/></Field><Field label={a.type==='move'?'Куда идти':a.type==='music'?'Музыкальная композиция':'Значение'}>{a.type==='move'?<Select value={a.value} onChange={v=>override('value',v)} options={['окно','стол','камин','диван']}/>:a.type==='weather'?<Select value={a.value} onChange={v=>override('value',v)} options={['Дождь','Гроза','Ясно']}/>:<input value={a.value} onChange={e=>override('value',e.target.value)}/>}</Field>{TYPES[a.type].completion==='FINITE'&&<Field label="Длительность постановки"><div className="input-unit"><input type="number" min="0.1" step="0.1" value={a.duration} onChange={e=>override('duration',Number(e.target.value))}/><span>сек</span></div></Field>}{Object.keys(binding.overrides).length>0&&<button className="text-button" onClick={()=>editBinding('overrides',{})}><Icon name="RotateCcw" size={12}/>Вернуть настройки шаблона</button>}</section>;})()}
   <section className="property-section"><h4>ВНУТРИ СОБЫТИЯ</h4>{event.groups.map((g,i)=><div className="mini-group" key={g.id}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{g.name}</strong>{g.actions.map(a=><small key={a.id}>{TYPES[a.type]?.label} · {targetName(project,a.target)}</small>)}</div></div>)}<button className="text-button" onClick={()=>{setEditingEvent(event.id);setWorkspace('library');setSelection({type:'event'});}}>Открыть редактор события<Icon name="ArrowUpRight" size={13}/></button></section>
   {issues.filter(i=>i.beatId===selectedBeat.id).map(i=><div className="inspector-error" key={i.id}><Icon name="CircleAlert" size={17}/><b>{i.title}</b><p>{i.detail}</p><Button onClick={()=>fix(i)}>{i.fix==='sequential'?'Выполнить по очереди':'Исправить настройки'}<Icon name="ArrowRight" size={13}/></Button></div>)}
   <button className="text-button danger" onClick={()=>{editBeat(b=>b.bindings.splice(selection.index,1));setSelection({type:'beat',beat:selectedBeat.id});}}>Убрать событие из реплики</button>
  </>:selection.type==='object'&&selectedObject?<>
   <div className="inspector-title"><span className="large-icon" style={{color:selectedObject.color}}><Icon name={selectedObject.type==='Персонаж'?'UserRound':'Box'} size={24}/></span><h2>{selectedObject.name}</h2><p>{selectedObject.type} · Гостиная</p></div>
   <Field label="Имя"><input value={selectedObject.name} onChange={e=>editObject('name',e.target.value)}/></Field><Field label="Цвет примитива"><input type="color" value={selectedObject.color} onChange={e=>editObject('color',e.target.value)}/></Field><Field label="Расположение"><Select value={selectedObject.position||'стол'} onChange={v=>editObject('position',v)} options={['окно','стол','камин','диван']}/></Field><label className="check-field"><input type="checkbox" checked={selectedObject.active} onChange={e=>editObject('active',e.target.checked)}/>Активен и виден в сцене</label>
   {selectedObject.type==='Активный меш'&&<section className="property-section"><h4>ВЗАИМОДЕЙСТВИЕ</h4><Field label="При клике игрока"><input value={selectedObject.interaction||'Осмотреть'} onChange={e=>editObject('interaction',e.target.value)}/></Field><div className="human-note"><Icon name="MousePointerClick"/><span>Клик по объекту отправляет сигнал сценарию. Блок ожидания сможет продолжить историю.</span></div></section>}
   <section className="property-section"><h4>ГДЕ ИСПОЛЬЗУЕТСЯ</h4>{project.events.filter(e=>e.groups.some(g=>g.actions.some(a=>a.target===selectedObject.id))).map(e=><button className="usage-link" key={e.id} onClick={()=>{setEditingEvent(e.id);setSelection({type:'event'});setWorkspace('library');}}><Icon name="Zap" size={13}/>{e.name}<Icon name="ArrowUpRight" size={12}/></button>)}</section><Button icon="Trash2" onClick={()=>{change(p=>{p.objects=p.objects.filter(o=>o.id!==selectedObject.id);});setSelection({type:'beat',beat:focus});notify('Объект удалён. Связанные действия проверены.');}}>Удалить объект</Button>
  </>:selection.type==='action'&&event?(()=>{const a=event.groups.find(g=>g.id===selection.groupId)?.actions.find(a=>a.id===selection.actionId);if(!a)return <p>Выберите действие в шаге.</p>;const set=(k,v)=>editAction(selection.groupId,a.id,k,v);return <>
   <div className="inspector-title"><span className="large-icon"><Icon name={TYPES[a.type]?.icon} size={24}/></span><h2>{TYPES[a.type]?.label}</h2><p>В шаблоне «{event.name}»</p></div><Field label="Тип действия"><Select value={a.type} onChange={v=>{set('type',v);set('wait',TYPES[v].completion==='CONTINUOUS'?'STARTED':'COMPLETED');set('scope',TYPES[v].completion==='CONTINUOUS'?'EVENT':'SELF');}} options={Object.entries(TYPES).map(([k,t])=>[k,t.label])}/></Field><Field label="Объект"><Select value={a.target} onChange={v=>set('target',v)} options={objectOptions}/></Field><Field label="Результат / параметр"><input value={a.value} onChange={e=>set('value',e.target.value)}/></Field><Field label="Когда перейти к следующему шагу"><Select value={a.wait} onChange={v=>set('wait',v)} options={TYPES[a.type].completion==='CONTINUOUS'?[['NONE','Сразу'],['STARTED','После запуска']]:[['NONE','Сразу'],['STARTED','После запуска'],['COMPLETED','После завершения']]}/></Field><Field label="Остановить самое позднее"><Select value={a.scope} onChange={v=>set('scope',v)} options={TYPES[a.type].completion==='CONTINUOUS'?[['GROUP','При закрытии шага'],['EVENT','При закрытии события']]:[['SELF','Закончится само'],['GROUP','При закрытии шага'],['EVENT','При закрытии события']]}/></Field>
   <section className="property-section"><h4>ЕСЛИ ЧТО-ТО ПОШЛО НЕ ТАК</h4><Field label="Если объект уже занят"><Select value={a.conflict} onChange={v=>set('conflict',v)} options={['FAIL_NEW','REPLACE_CURRENT','QUEUE'].map(x=>[x,{FAIL_NEW:'Сообщить об ошибке',REPLACE_CURRENT:'Остановить предыдущее',QUEUE:'Очередь · исследовательский режим'}[x]])}/></Field><Field label="При ошибке"><Select value={a.onFailure} onChange={v=>set('onFailure',v)} options={['Остановить событие','Пропустить действие','Безопасный исход']}/></Field><details><summary>Ограничения и завершение</summary>{[['queueTimeout','Ожидание ресурса'],['startTimeout','Подтверждение запуска'],['executionTimeout','Выполнение'],['stopTimeout','Остановка и очистка']].map(([key,label])=><Field key={key} label={`${label}, сек`}><input type="number" min="0" value={a[key]} onChange={e=>set(key,Number(e.target.value))}/></Field>)}<Field label="После успеха"><input value={a.finalState} onChange={e=>set('finalState',e.target.value)}/></Field><Field label="После ошибки"><input value={a.fallback} onChange={e=>set('fallback',e.target.value)}/></Field>{a.waitFor&&<Field label="Ожидает событие"><Select value={a.waitFor} onChange={v=>set('waitFor',v)} options={[['','Внешний сигнал'],...project.events.map(e=>[e.id,e.name])]}/></Field>}</details></section><div className="human-note"><Icon name="Shield"/><span>Ресурс: {targetName(project,a.target)} · {TYPES[a.type].domain||'Без захвата ресурса'}. Определяется типом действия.</span></div>
   </>;})():selection.type==='event'&&event?<>
   <div className="inspector-title"><span className="large-icon"><Icon name="Shapes" size={24}/></span><h2>{event.name}</h2><p>Изменения применяются ко всем размещениям</p></div><Field label="Описание"><textarea value={event.description} onChange={e=>editEvent('description',e.target.value)}/></Field><Field label="После выполнения всех шагов"><Select value={event.retention} onChange={v=>{editEvent('retention',v);if(v==='HOLD_UNTIL_REPLACED'&&!event.channel)editEvent('channel','Audio.BGM');}} options={[["AUTO_CLOSE_ON_FLOW_END","Завершить событие"],["HOLD_UNTIL_STOPPED","Оставить до остановки"],["HOLD_UNTIL_REPLACED","Оставить до замены"]]}/></Field><Field label="Действует в пределах"><Select value={event.owner} onChange={v=>editEvent('owner',v)} options={['SubScene','Scene','GameSession'].map(x=>[x,{SubScene:'Этой сабсцены',Scene:'Всей сцены',GameSession:'Игровой сессии'}[x]])}/></Field>{event.retention==='HOLD_UNTIL_REPLACED'&&<Field label="Что заменяет это событие" hint="Общая роль нужна только фоновым событиям."><Select value={event.channel} onChange={v=>editEvent('channel',v)} options={[["Audio.BGM","Фоновая музыка"],["World.Weather","Погода"],["Camera.Mode","Режим камеры"]]}/></Field>}<div className="human-note"><Icon name="Info"/><span>Выполненные шаги и завершённое событие — разные состояния. Фоновое событие остаётся активно после своих шагов.</span></div><section className="property-section"><h4>РАЗМЕЩЕНИЯ В СЦЕНАРИИ</h4>{beats.filter(b=>b.bindings.some(x=>x.eventId===event.id)).map(b=><button className="usage-link" key={b.id} onClick={()=>reveal(b.id)}><Icon name="MessageSquare" size={13}/><span>{b.text}</span><Icon name="ArrowUpRight" size={12}/></button>)}</section>
  </>:<>
   <div className="inspector-title"><span className="large-icon"><Icon name={current.kind==='choice'?'GitBranch':current.kind==='gate'?'MousePointer2':'MessageSquare'} size={24}/></span><h2>{selectedBeat.kind==='choice'?'Выбор игрока':selectedBeat.kind==='gate'?'Ожидание игрока':'Реплика'}</h2><p>{project.chapters.find(c=>c.beats.some(b=>b.id===selectedBeat.id))?.name}</p></div>
   <Field label="Кто говорит"><Select value={selectedBeat.speaker} onChange={v=>editBeat(b=>b.speaker=v)} options={['Рассказчик',...project.objects.filter(o=>o.type==='Персонаж').map(o=>o.name)]}/></Field><Field label="Текст"><textarea rows="4" value={selectedBeat.text} onChange={e=>editBeat(b=>b.text=e.target.value)}/></Field>
   {selectedBeat.kind==='choice'&&<section className="property-section"><h4>ВАРИАНТЫ И УСЛОВИЯ</h4>{selectedBeat.choices.map((c,i)=><div className="choice-editor" key={c.id}><input aria-label={`Ответ ${i+1}`} value={c.label} onChange={e=>editBeat(b=>b.choices[i].label=e.target.value)}/><Select value={c.condition} onChange={v=>editBeat(b=>b.choices[i].condition=v)} options={[["always","Доступно всегда"],["trust","Если доверие достаточно"],["letter","Если найдено письмо"]]}/>{c.condition==='trust'&&<input aria-label="Минимальное доверие" type="number" value={c.threshold||0} onChange={e=>editBeat(b=>b.choices[i].threshold=Number(e.target.value))}/>}<Field label="Перейти к блоку"><Select value={c.next||''} onChange={v=>editBeat(b=>b.choices[i].next=v)} options={[["","Следующий общий блок"],...beats.filter(b=>b.id!==selectedBeat.id).map(b=>[b.id,b.text.slice(0,36)])]}/></Field></div>)}<Button icon="Plus" onClick={()=>editBeat(b=>b.choices.push({id:uid('choice'),label:'Новый ответ',condition:'always'}))}>Добавить ответ</Button></section>}
   {selectedBeat.kind==='gate'&&<><Field label="Какое действие ждём"><Select value={selectedBeat.signal} onChange={v=>editBeat(b=>b.signal=v)} options={project.objects.filter(o=>o.type==='Активный меш').map(o=>[o.id,`${o.name} → ${o.interaction||'Осмотреть'}`])}/></Field><Field label="Подсказать через, сек" hint="Это время до подсказки, не ограничение для игрока."><input type="number" value={selectedBeat.timeout} onChange={e=>editBeat(b=>b.timeout=Number(e.target.value))}/></Field></>}
   <section className="property-section"><h4>СОБЫТИЯ У РЕПЛИКИ</h4>{HOOKS.map(([key,label])=><div className="hook-row" key={key}><strong>{label}</strong><small>{selectedBeat.bindings.filter(b=>b.hook===key).length} событий</small><button title={`Добавить: ${label}`} onClick={()=>{setFocus(selectedBeat.id);setModal({type:'attach',beatId:selectedBeat.id,hook:key});}}><Icon name="Plus" size={13}/></button></div>)}<Button icon="Plus" onClick={()=>setModal({type:'attach',beatId:selectedBeat.id})}>Добавить событие</Button></section>
   <section className="property-section"><h4>ПРОВЕРОЧНЫЕ УСЛОВИЯ</h4><Field label={`Доверие Алисы: ${state.variables.trust}`}><input type="range" min="0" max="5" value={state.variables.trust} onChange={e=>run?setRun(r=>({...r,variables:{...r.variables,trust:Number(e.target.value)}})):change(p=>{p.variables.trust=Number(e.target.value);})}/></Field><label className="check-field"><input type="checkbox" checked={state.variables.letter} onChange={e=>run?setRun(r=>({...r,variables:{...r.variables,letter:e.target.checked}})):change(p=>{p.variables.letter=e.target.checked;})}/>Письмо найдено</label></section>
  </>}
  </div><div className="inspector-footer"><Icon name="Info" size={13}/>{run?'Предпросмотр использует свой снимок состояния':'Изменения сохраняются автоматически'}</div></aside>}
  <footer className="statusbar"><span><Icon name="Circle" size={8}/>Локальный макет <i>·</i> {titleCount} реплик <i>·</i> {project.events.length} шаблонов событий</span><button onClick={()=>setChecksOpen(true)} className={issues.length?'error-text':''}><Icon name={issues.length?'CircleAlert':'CheckCheck'} size={12}/>{issues.length?`${issues.length} ошибки требуют внимания`:'Ошибок не найдено'}</button><span>Сценарий привязан к репликам, не к секундам <Icon name="Keyboard" size={13}/></span></footer>
  {toast&&<div className="toast" role="status"><Icon name="Info" size={16}/>{toast}</div>}
  {checksOpen&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setChecksOpen(false)}><section className="checks-panel" role="dialog" aria-modal="true" aria-label="Проверка проекта"><div className="modal-heading"><div><div className="eyebrow">ДИАГНОСТИКА СЦЕНАРИЯ</div><h2>{issues.length?'Давайте распутаем историю':'Всё готово к предпросмотру'}</h2></div><button aria-label="Закрыть проверку" onClick={()=>setChecksOpen(false)}><Icon name="X" size={20}/></button></div><p className="modal-description">Проверены размещения, действия, объекты и цепочки ожиданий. Исправления меняют настройки проекта.</p><div className="check-summary"><Tag tone={issues.length?'red':'green'} icon={issues.length?'CircleAlert':'ShieldCheck'}>{issues.length} ошибок</Tag><span>{beats.length} блоков · {project.events.length} шаблонов · {project.objects.length} объектов</span></div><div className="issue-list">{issues.map((i,index)=><div className="issue-card" key={i.id}><span className="issue-number">{String(index+1).padStart(2,'0')}</span><div><h3>{i.title}</h3><p>{i.detail}</p><div className="issue-location"><Icon name="MapPin" size={12}/>{project.chapters.find(c=>c.beats.some(b=>b.id===i.beatId))?.name||'Библиотека'}<span>→</span>{i.beatId}</div><div className="issue-actions"><Button onClick={()=>{if(i.beatId)reveal(i.beatId);else{setEditingEvent(i.eventId);setWorkspace('library');setSelection({type:'event'});}setChecksOpen(false);}} icon="ArrowUpRight">Показать место</Button><Button className="subtle" onClick={()=>fix(i)} icon="WandSparkles">{i.fix==='sequential'?'Выполнить по очереди':i.fix==='break-cycle'?'Ждать внешнего сигнала':i.fix==='split-group'?'Разнести по шагам':'Исправить настройки'}</Button></div></div></div>)}{!issues.length&&<div className="check-success"><Icon name="ShieldCheck" size={50}/><h3>История может продолжаться</h3><p>Все обнаруженные конфликты устранены.</p><Button className="primary" icon="Play" onClick={()=>{setChecksOpen(false);startPreview();}}>Протестировать сцену</Button></div>}</div><div className="check-footer"><Icon name="FlaskConical" size={16}/><span>Исследовать краевые случаи</span><Select value="" onChange={v=>{if(v==='held'){change(p=>{const b=allBeats(p).find(b=>b.bindings.some(x=>x.eventId==='bgm'));if(b)b.bindings.find(x=>x.eventId==='bgm').join='EVENT_END';});}if(v==='loop')change(p=>{const a=p.events.find(e=>e.id==='bgm')?.groups[0].actions[0];if(a)a.wait='COMPLETED';});if(v==='missing')change(p=>{p.objects=p.objects.filter(o=>o.id!=='alice');});if(v==='choices')change(p=>{allBeats(p).find(b=>b.kind==='choice').choices.forEach(c=>{c.condition='trust';c.threshold=9;});});}} options={[["","Добавить проблемный пример…"],["held","Музыка блокирует следующую реплику"],["loop","Ожидание конца зацикленной музыки"],["missing","Удалён персонаж, нужный действиям"],["choices","Все ответы имеют условия"]]}/></div></section></div>}
  {searchOpen&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setSearchOpen(false)}><div className="search-dialog" role="dialog" aria-label="Поиск в сценарии"><div className="search-input"><Icon name="Search" size={21}/><input autoFocus placeholder="Найти реплику, событие или персонажа…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>setSearchOpen(false)}>Esc</button></div><div className="search-results">{beats.filter(b=>query&&`${b.text} ${b.speaker} ${b.bindings.map(x=>project.events.find(e=>e.id===x.eventId)?.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0,30).map(b=><button key={b.id} onClick={()=>{reveal(b.id);setSearchOpen(false);}}><Icon name="MessageSquare"/><span><strong>{b.text}</strong><small>{b.speaker} · {project.chapters.find(c=>c.beats.some(x=>x.id===b.id))?.name}</small></span><Icon name="ArrowUpLeft" size={14}/></button>)}{!query&&<p>Поиск по всей истории, включая свёрнутые ветки.</p>}{query&&!beats.some(b=>`${b.text} ${b.speaker}`.toLowerCase().includes(query.toLowerCase()))&&<p>Найдены все доступные совпадения.</p>}</div></div></div>}
  {modal&&<Modal modal={modal} close={()=>setModal(null)} project={project} change={change} current={current} chapter={chapter} editingEvent={editingEvent} setEditingEvent={setEditingEvent} setSelection={setSelection} setWorkspace={setWorkspace} addBinding={addBinding} notify={notify} state={state} run={run} reveal={reveal} exportProject={exportProject}/>}
 </div>;
}

function Modal({modal,close,project,change,current,chapter,editingEvent,setEditingEvent,setSelection,setWorkspace,addBinding,notify,state,run,reveal,exportProject}){
 const [name,setName]=useState(''),[kind,setKind]=useState(modal.actionType||'move'),[objectType,setObjectType]=useState('Персонаж'),[target,setTarget]=useState('alice'),[value,setValue]=useState('окно'),[filter,setFilter]=useState('');
 const titles={object:'Добавить объект',event:modal.category==='Группы'?'Создать группу действий':modal.category==='Действия'?'Создать действие':'Создать событие',action:'Добавить действие',group:'Выбрать готовую группу',attach:'Добавить событие к реплике',beat:'Добавить блок сценария',chapter:'Новый эпизод',help:'От идеи к живой сцене',project:'Проект и данные',runtime:'Что сейчас происходит'};
 const submit=e=>{e.preventDefault();
  if(modal.type==='object'){const id=uid('object');change(p=>p.objects.push({id,name:name.trim(),type:objectType,color:'#b6a1e1',active:true,position:'стол',interaction:objectType==='Активный меш'?'Осмотреть':undefined}));setSelection({type:'object',id});notify('Объект добавлен в гостиную');}
  if(modal.type==='event'){const id=uid('event');const a=makeAction(kind,target,value);change(p=>{p.events.push({id,name:name.trim(),description:'Ваше событие',retention:TYPES[kind].completion==='CONTINUOUS'?'HOLD_UNTIL_STOPPED':'AUTO_CLOSE_ON_FLOW_END',owner:'SubScene',groups:[{id:uid('group'),name:modal.category==='Группы'?name.trim():'Основное действие',actions:[a]}]});});setEditingEvent(id);setSelection({type:'event'});setWorkspace('library');notify('Шаблон создан. Теперь его можно добавить в сцену.');}
  if(modal.type==='action')change(p=>{p.events.find(ev=>ev.id===editingEvent).groups.find(g=>g.id===modal.groupId).actions.push(makeAction(kind,target,value));});
  if(modal.type==='chapter'){const id=uid('chapter'),bid=uid('beat');change(p=>{p.chapters.push({id,name:name.trim(),description:'Новый эпизод',beats:[{id:bid,kind:'dialogue',speaker:'Рассказчик',text:'Здесь начинается новый эпизод.',mode:'SEQUENTIAL',bindings:[]}]});});notify('Эпизод добавлен в структуру слева');}
  if(modal.type==='beat'){const id=uid('beat'),bk=['dialogue','choice','gate'].includes(kind)?kind:'dialogue';change(p=>{p.chapters.find(c=>c.id===(modal.chapterId||chapter)).beats.push({id,kind:bk,speaker:'Алиса',text:name.trim(),mode:'SEQUENTIAL',bindings:[],...(bk==='choice'?{choices:[{id:uid('choice'),label:'Продолжить',condition:'always'}]}:{}),...(bk==='gate'?{signal:'letter',timeout:45,fallback:'Подсветить письмо'}:{})});});setTimeout(()=>reveal(id),50);notify('Блок добавлен в конец эпизода');}
  close();
 };
 return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className={`modal ${['help','runtime','attach','group'].includes(modal.type)?'wide':''}`} role="dialog" aria-modal="true" aria-label={titles[modal.type]}><div className="modal-heading"><div><div className="eyebrow">SACURA STUDIO</div><h2>{titles[modal.type]}</h2></div><button aria-label="Закрыть окно" onClick={close}><Icon name="X" size={20}/></button></div>
 {modal.type==='group'?<><p className="modal-description">Готовый шаг копируется в конец текущего события. Его действия начнутся вместе.</p><div className="attach-list">{project.events.flatMap(e=>e.groups.map(g=>({g,e}))).map(({g,e})=><button key={g.id} onClick={()=>{change(p=>{p.events.find(ev=>ev.id===editingEvent).groups.push({...structuredClone(g),id:uid('group'),actions:g.actions.map(a=>({...structuredClone(a),id:uid('action')}))});});close();notify('Группа добавлена в событие');}}><Icon name="Layers"/><span><strong>{g.name}</strong><small>{e.name} · {g.actions.length} действий</small></span><Icon name="Plus"/></button>)}</div></>:modal.type==='attach'?<><p className="modal-description">К блоку «{allBeats(project).find(b=>b.id===modal.beatId)?.text||current.text}»</p><div className="search-input compact"><Icon name="Search"/><input autoFocus placeholder="Поиск события…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="attach-list">{project.events.filter(e=>e.name.toLowerCase().includes(filter.toLowerCase())).map(e=><button key={e.id} onClick={()=>{addBinding(e.id,modal.beatId||current.id);if(modal.hook)change(p=>{allBeats(p).find(b=>b.id===(modal.beatId||current.id)).bindings.at(-1).hook=modal.hook;});}}><span className="large-icon"><Icon name={TYPES[e.groups[0]?.actions[0]?.type]?.icon}/></span><span><strong>{e.name}</strong><small>{e.groups.length} шагов · {e.retention==='AUTO_CLOSE_ON_FLOW_END'?'Завершается само':'Работает в фоне'}</small></span><Icon name="Plus"/></button>)}</div></>
 :modal.type==='help'?<><p className="modal-description">Сценарий читается сверху вниз, как история. Раскрывайте только тот эпизод, над которым работаете.</p><div className="help-grid">{[['ListTree','01','Напишите историю','Реплики, выборы и ожидания живут в ленте. Карта показывает, куда ведут ответы и где ветки сходятся.'],['Shapes','02','Соберите постановку','В библиотеке создайте событие из шагов. Шаги идут по очереди; действия внутри шага — вместе.'],['MousePointer2','03','Добавьте к реплике','Выберите «до», «с репликой» или «после». Настройки размещения меняют только это место истории.'],['ShieldCheck','04','Проверьте и пройдите','Ошибки ведут к проблемному месту. В предпросмотре выбирайте ответы, осматривайте письмо и проверяйте условия.']].map(([icon,n,t,d])=><div key={n}><Icon name={icon} size={24}/><small>{n}</small><h3>{t}</h3><p>{d}</p></div>)}</div><div className="help-note"><Icon name="Info"/><p>Макет моделирует UX. Время выполнения действий, аудио и очистка ресурсов показаны упрощённо. Спецификация C++-движка остаётся отдельной.</p></div><Button className="primary" onClick={close}>Вернуться к истории</Button></>
 :modal.type==='runtime'?<><p className="modal-description">{run?'Снимок текущего предпросмотра. Экземпляры отделены от шаблонов.':'Запустите предпросмотр, чтобы увидеть экземпляры событий. Сейчас показано начальное состояние сцены.'}</p><div className="runtime-state"><Tag tone="green" icon="Music2">{state.musicState==='playing'?'Музыка играет':state.musicState==='paused'?'Музыка на паузе':'Музыка остановлена'}</Tag><Tag tone="blue" icon="CloudRain">{state.weather}</Tag><Tag tone="amber" icon="Sun">{state.time}</Tag><Tag tone="purple">Доверие: {state.variables.trust}</Tag></div><div className="runtime-list">{run?.instances.slice().reverse().map(i=><div key={i.id}><Icon name={i.state==='HELD'?'Waves':'CheckCheck'}/><span><strong>{i.name}</strong><small>{i.id.slice(0,16)} · {i.owner} · шаги выполнены</small></span><Tag tone={i.state==='HELD'?'green':'gray'}>{i.state==='HELD'?'Работает в фоне':'Завершено'}</Tag></div>)}</div><div className="help-note"><Icon name="Shield"/><p>При завершении владельца: остановка → очистка → освобождение ресурсов. В этом UX-макете конечные действия применяются сразу; длительности и таймауты не являются настоящим планировщиком.</p></div></>
 :modal.type==='project'?<><p className="modal-description">Изменения сохраняются в этом браузере. Экспортируйте JSON, чтобы перенести макет на другой компьютер.</p><Button icon="Download" className="primary" onClick={exportProject}>Скачать проект</Button><div className="property-section"><h4>ДЕМОНСТРАЦИОННЫЕ ДАННЫЕ</h4><p>Восстановить исходную сложную сцену вместе с намеренными ошибками.</p><Button icon="RotateCcw" onClick={()=>{change(createProject());setWorkspace('scene');notify('Демонстрационная сцена восстановлена');close();}}>Восстановить демо</Button></div></>
 :<form onSubmit={submit}>
  {modal.type!=='action'&&<Field label={modal.type==='beat'?'Текст блока':'Название'}><input autoFocus required placeholder={modal.type==='object'?'Например, Смотритель':modal.type==='event'?'Например, Подойти и поздороваться':modal.type==='chapter'?'Например, Ночь в саду':'Что произойдёт в истории?'} value={name} onChange={e=>setName(e.target.value)}/></Field>}
  {modal.type==='object'&&<><Field label="Тип объекта"><div className="creation-types">{[['Персонаж','UserRound'],['Активный меш','MousePointer2'],['Меш','Box']].map(([t,icon])=><button type="button" className={objectType===t?'active':''} onClick={()=>setObjectType(t)} key={t}><Icon name={icon} size={23}/>{t}</button>)}</div></Field><p className="modal-description">{objectType==='Персонаж'?'Персонажа можно двигать, анимировать и использовать в диалогах.':objectType==='Активный меш'?'Объект, который игрок может осмотреть или нажать.':'Декорация сцены, которую можно показать или скрыть.'} В макете появится простой примитив.</p></>}
  {['event','action'].includes(modal.type)&&<><Field label="Что сделать"><Select value={kind} onChange={v=>{setKind(v);setTarget(['music','pause','resume','stop','duck'].includes(v)?'audio':['weather','time','sound'].includes(v)?'world':v==='camera'?'camera':'alice');setValue(v==='move'?'окно':v==='weather'?'Дождь':v==='time'?'Ночь':v==='music'?'After the rain':v==='pose'?'улыбка':'Значение');}} options={Object.entries(TYPES).map(([k,t])=>[k,t.label])}/></Field><Field label="С каким объектом"><Select value={target} onChange={setTarget} options={[...project.objects.map(o=>[o.id,o.name]),['world','Мир'],['audio','Музыка'],['camera','Главная камера'],['trust','Доверие']]}/></Field><Field label="Куда / какое значение"><input required value={value} onChange={e=>setValue(e.target.value)}/></Field><div className="human-note"><Icon name="Sparkles"/><span>Ожидание и время жизни настроятся по типу действия. Их можно уточнить в свойствах.</span></div></>}
  {modal.type==='beat'&&<Field label="Тип блока"><Select value={['dialogue','choice','gate'].includes(kind)?kind:'dialogue'} onChange={setKind} options={[["dialogue","Реплика"],["choice","Выбор игрока"],["gate","Ожидание взаимодействия"]]}/></Field>}
  <div className="modal-footer"><Button type="button" onClick={close}>Отмена</Button><Button type="submit" className="primary" icon="Plus">{modal.type==='action'?'Добавить действие':'Создать'}</Button></div>
 </form>}
 {modal.type==='runtime'&&<FailureLab/>}
 </section></div>;
}
