import React from 'react';
import {Icon,Button} from './StudioParts.jsx';
import {cameraPose} from './cameraModel.js';

export default function CameraWorkspace({scene,objects,state,selected,onSelect,onCreate,onFollow,onChange,onDefault,onDelete,onPilot,onView,onCapture,piloting,running,onEdit}){
 const cameras=scene.cameras||[],c=cameras.find(c=>c.id===selected)||cameras[0],characters=objects.filter(o=>o.type==='Персонаж'&&o.active!==false),pose=c?cameraPose(c,state,objects,scene.kind):null;
 const patch=v=>onChange(c.id,v);
 const range=(key,label,min,max,step,unit)=> <label className="camera-range"><span>{label}<b>{Number(c[key]).toFixed(step<1?1:0)}{unit}</b></span><input type="range" min={min} max={max} step={step} value={c[key]} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>;
 return <div className="camera-workspace"><header><div><strong><Icon name="Video"/> Камеры</strong><small>{scene.location} · {cameras.length} ракурсов</small></div><Button icon="Plus" disabled={running} onClick={onCreate}>Камера из вида</Button><Button icon="UserRoundCheck" disabled={running||!characters.length} onClick={onFollow}>Следить за персонажем</Button></header>
  {running&&<div className="camera-running">Настройки сохранённой постановки <Button icon="Square" onClick={onEdit}>Остановить и редактировать</Button></div>}
  <div className="camera-workspace-body"><aside>{cameras.map(camera=><button className={c?.id===camera.id?'active':''} key={camera.id} onClick={()=>onSelect(camera.id)}><Icon name={camera.mode==='follow'?'UserRoundCheck':'Video'}/><span>{camera.name}<small>{camera.id===scene.defaultCameraId?'Основная · ':''}{camera.mode==='follow'?'Слежение':'Фиксированный кадр'}</small></span></button>)}<p>Наведите свободный вид мышью и нажмите «Камера из вида». Камеры также можно двигать за цветные оси в 3D.</p></aside>
   {c?<main><div className="camera-heading"><input aria-label="Название камеры" value={c.name} disabled={running} onChange={e=>patch({name:e.target.value})}/><Button icon={c.id===scene.defaultCameraId?'Star':'StarOff'} disabled={running||c.id===scene.defaultCameraId} onClick={()=>onDefault(c.id)}>{c.id===scene.defaultCameraId?'Основная':'Сделать основной'}</Button></div>
    <div className="camera-shot-actions"><Button icon="Eye" onClick={()=>onView(c.id)}>Посмотреть</Button><Button icon="Move" disabled={running} className={piloting===c.id?'active':''} onClick={()=>onPilot(c.id)}>Настроить ракурс мышью</Button><Button icon="ScanLine" disabled={running} onClick={()=>onCapture(c.id)}>Сохранить текущий вид</Button></div>
    <fieldset disabled={running}><div className="camera-mode"><button className={c.mode==='fixed'?'active':''} onClick={()=>patch({mode:'fixed',position:pose.position,target:pose.target})}><Icon name="Video"/>Стоит на месте</button><button disabled={!characters.length} className={c.mode==='follow'?'active':''} onClick={()=>patch({mode:'follow',followTargetId:c.followTargetId||characters[0]?.id})}><Icon name="UserRoundCheck"/>Следует за персонажем</button></div>
    {c.mode==='follow'&&<><label className="camera-target">Персонаж<select value={c.followTargetId||''} onChange={e=>patch({followTargetId:e.target.value})}><option value="" disabled>Выберите персонажа</option>{!characters.some(o=>o.id===c.followTargetId)&&c.followTargetId&&<option value={c.followTargetId}>Персонаж недоступен</option>}{characters.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label>{pose.targetMissing?<p className="camera-error">Цель скрыта или отсутствует в этой сабсцене. Используется сохранённый неподвижный кадр.</p>:<p className="camera-follow-note">Камера движется вместе с персонажем и держит его в кадре, в том числе во время событий перемещения.</p>}</>}
    <div className="camera-lens-grid">{range('fov','Угол обзора',20,90,1,'°')}{range('smoothing','Плавность',0,2,.1,' с')}{c.mode==='follow'&&<>{range('distance','Расстояние',.6,10,.1,' м')}{range('height','Высота камеры',.3,5,.1,' м')}{range('yaw','Ракурс вокруг героя',-180,180,1,'°')}{range('targetHeight','Смотреть на высоту',.2,1.6,.1,' м')}</>}</div>
    <details className="camera-coordinates"><summary>Точные координаты кадра</summary>{['position','target'].map(key=><label key={key}><span>{key==='position'?'Камера XYZ':'Точка взгляда XYZ'}</span><div>{c[key].map((value,i)=><input aria-label={`${key==='position'?'Камера':'Точка взгляда'} ${'XYZ'[i]}`} key={i} type="number" step=".1" value={Number(value.toFixed(2))} disabled={c.mode==='follow'} onChange={e=>patch({[key]:c[key].map((n,j)=>i===j?Number(e.target.value):n)})}/>)}</div></label>)}</details></fieldset>
    <footer><span>Основная камера используется для «Общего плана». Другую можно выбрать действием «Сменить план».</span><Button icon="Trash2" disabled={running} onClick={()=>onDelete(c.id)}>Удалить</Button></footer>
   </main>:<main className="camera-empty"><Icon name="Video" size={30}/><p>Сохраните первый ракурс из текущего вида сцены.</p><Button icon="Plus" disabled={running} onClick={onCreate}>Камера из вида</Button></main>}
  </div>
 </div>;
}
