import React,{useEffect,useRef} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import Scene from './Scene.jsx';

function Exterior({kind,objects,state,onSelect,onInteract}){
 const host=useRef(),live=useRef();live.current={state,onSelect,onInteract};
 useEffect(()=>{let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{host.current.textContent='3D недоступно · используйте кнопки объектов ниже';return;}
 const element=host.current;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#18212a');element.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(8,7,10);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.6,0);controls.enableDamping=true;controls.enablePan=false;controls.maxPolarAngle=1.45;scene.add(new THREE.HemisphereLight(0xc5d7ea,0x253831,2));const sun=new THREE.DirectionalLight(0xffd5ac,2);sun.position.set(-4,9,3);scene.add(sun);const picks=[];const box=(w,h,d,x,y,z,color,id)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.8}));mesh.position.set(x,y,z);scene.add(mesh);if(id){mesh.userData.id=id;picks.push(mesh);}return mesh;};
 if(kind==='garden'){box(9,.2,7,0,-.15,0,'#3c544b');box(1.6,.025,7,0,0,0,'#899286');for(const [x,z]of[[-3,-2],[3,-2],[-3,2],[3,2]]){box(.25,2,.25,x,.9,z,'#776358');const leaves=new THREE.Mesh(new THREE.IcosahedronGeometry(1.35,0),new THREE.MeshStandardMaterial({color:'#527b68'}));leaves.position.set(x,2.7,z);scene.add(leaves);}box(2,.18,.6,2,.65,.5,'#a49076');box(2,.65,.12,2,1,.8,'#887861');box(.4,.018,.25,2,.76,.4,'#efdfb7','garden-note');for(const x of[1.25,2.75])box(.12,.6,.4,x,.3,.5,'#6c6b68');box(3,.6,.2,-2,.3,-3,'#6e8272');}
 else{box(9,.2,6,0,-.1,0,'#687575');for(const z of[-1.6,-2.4])box(10,.07,.08,0,.06,z,'#b7b6ab');for(let x=-4;x<5;x+=.7)box(.12,.06,1,x,.02,-2,'#5c534e');box(7,1.8,1.5,0,1,-2,'#638c8c');for(let x=-2.5;x<3;x+=1.2)box(.8,.65,.05,x,1.2,-1.22,'#e3c58d');box(5,.14,2,0,2.8,1,'#9aaba3');for(const x of[-2,2])box(.12,2.8,.12,x,1.4,1.4,'#829a91');box(.65,.8,.4,1.4,.4,1.2,'#aaa39a');box(.4,.018,.26,1.4,.82,1.2,'#e6d6b5','ticket');}
 const chars=[];objects.filter(o=>o.type==='Персонаж').forEach((o,i)=>{const g=new THREE.Group(),mat=new THREE.MeshStandardMaterial({color:o.color});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.23,.55,4,12),mat);body.position.y=.7;const head=new THREE.Mesh(new THREE.SphereGeometry(.19,16,12),new THREE.MeshStandardMaterial({color:'#dfc6af'}));head.position.y=1.26;g.add(body,head);g.position.set(-.6+i*1.3,0,.4);g.userData.id=o.id;scene.add(g);picks.push(g);chars.push(g);});const grid=new THREE.GridHelper(20,20,0x344d4d,0x293b3d);grid.position.y=-.25;scene.add(grid);
 const rainPoints=[];for(let i=0;i<65;i++){const x=Math.random()*8-4,y=Math.random()*4,z=Math.random()*6-3;rainPoints.push(x,y,z,x-.04,y-.18,z);}const rainGeo=new THREE.BufferGeometry();rainGeo.setAttribute('position',new THREE.Float32BufferAttribute(rainPoints,3));const rain=new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:0xa9c0d8,transparent:true,opacity:.3}));scene.add(rain);
 const ro=new ResizeObserver(()=>{const {width,height}=element.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix();});ro.observe(element);let down;const ray=new THREE.Raycaster();const press=e=>down=[e.clientX,e.clientY];const click=e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=element.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);let hit=ray.intersectObjects(picks,true)[0]?.object;if(hit){while(!hit.userData.id&&hit.parent)hit=hit.parent;live.current.onSelect?.(hit.userData.id);live.current.onInteract?.(hit.userData.id);}};renderer.domElement.addEventListener('pointerdown',press);renderer.domElement.addEventListener('pointerup',click);let frame;const render=()=>{frame=requestAnimationFrame(render);controls.update();sun.intensity=live.current.state.time==='Ночь'?.7:2.6;rain.visible=live.current.state.weather!=='Ясно';if(live.current.state.weatherPaused!==true)rain.position.y=-(Date.now()%900)/900*.2;renderer.render(scene,camera);};render();return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();scene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});renderer.dispose();renderer.domElement.remove();};
 },[kind,objects]);return <div ref={host} className="scene-canvas" aria-label={kind==='garden'?'3D сад с запиской на скамье':'3D станция с билетом'}/>;
}
export default function LocationScene(props){return (props.kind||props.state.location)==='living'?<Scene {...props} onLetter={()=>props.onInteract?.('letter')}/>:<Exterior {...props} kind={props.kind||props.state.location}/>;}
