import React,{useEffect,useState} from 'react';
import {Icon,Button} from './StudioParts.jsx';
import SubsceneMap from './SubsceneMap.jsx';
import {LOCATION_TEMPLATES,beatsInScene,newSceneDraft,sceneTransitions} from './subsceneModel.js';
import {isObjectInScene} from './sceneEditing.js';

export default function SubsceneWorkspace({project,scene,beat,request,draft:storedDraft,onDraftChange,running,onStop,onSelect,onCreate,onDuplicate,onPatch,onKind,onEntry,onConnect,onDisconnect,onOpenBeat,onScene,onCameras,onCreateRequest,onCancel}){
 const [view,setView]=useState('settings'),[creating,setCreating]=useState(request?.mode==='create'),[query,setQuery]=useState(''),[error,setError]=useState(''),[reroute,setReroute]=useState(true);
 useEffect(()=>{if(request?.mode==='create'){setCreating(true);setError('');}else setCreating(false);},[request?.token]);
 const lines=beatsInScene(project,scene.id),links=sceneTransitions(project,scene.id),cast=project.objects.filter(o=>o.type==='Персонаж'&&(!o.subsceneId||o.subsceneId===scene.id)),incoming=links.filter(l=>l.target===scene.id),outgoing=links.filter(l=>l.source===scene.id);
 const draft=storedDraft||newSceneDraft(project);
 const patch=v=>onDraftChange({...draft,...v});
 const create=()=>{if(!draft.name.trim()){setError('Назовите сабсцену — это её имя в списке и на карте.');return;}const message=onCreate(draft);if(message)setError(message);else{setCreating(false);setView('settings');}};
 const select=id=>{setCreating(false);setView('settings');setError('');onSelect(id);};
 return <div className="subscene-workspace"><header><div><strong><Icon name="PanelsTopLeft"/>Сабсцены</strong><small>{project.subscenes.length} локаций истории</small></div><div className="subscene-view-tabs">{[['settings','Settings2','Редактор'],['links','GitBranch','Переходы'],['map','Network','Карта']].map(([id,icon,label])=><button className={!creating&&view===id?'active':''} key={id} onClick={()=>{setCreating(false);setView(id);onCancel();}}><Icon name={icon} size={14}/>{label}</button>)}</div><Button icon="Plus" className="subscene-primary" disabled={running} onClick={onCreateRequest}>Добавить сабсцену</Button></header>
 {running&&<div className="camera-running">Идёт воспроизведение. Для редактирования остановите его.<Button icon="Square" onClick={onStop}>Остановить</Button></div>}
 {view==='map'&&!creating?<SubsceneMap project={project} current={scene.id} onOpen={onOpenBeat} onEdit={select} onCreate={onCreateRequest}/>:<div className="subscene-workspace-body"><aside><label className="subscene-search"><Icon name="Search" size={13}/><input aria-label="Найти сабсцену" placeholder="Найти сабсцену…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="subscene-manager-list">{project.subscenes.filter(s=>(s.name+' '+s.location).toLowerCase().includes(query.toLowerCase())).map((s,i)=>{const transitions=sceneTransitions(project,s.id),count=beatsInScene(project,s.id).length;return <button key={s.id} className={!creating&&scene.id===s.id?'active':''} onClick={()=>select(s.id)}><b>{String(i+1).padStart(2,'0')}</b><Icon name={LOCATION_TEMPLATES.find(t=>t.id===s.kind)?.icon||'Box'} size={18}/><span>{s.name}<small>{s.location} · {count} блоков</small>{i!==0&&!transitions.some(t=>t.target===s.id)&&<em>Нет входящего перехода</em>}</span></button>;})}</div><p>Сабсцена — локация со своим сценарием, объектами, окружением и камерами. Порядок истории задают переходы.</p></aside>
 <main>{creating?<>
  <div className="subscene-edit-heading"><div><small>НОВАЯ САБСЦЕНА</small><h2>Новый фрагмент истории</h2></div><Button icon="X" onClick={()=>{setCreating(false);onCancel();}}>Отмена</Button></div>
  <fieldset disabled={running}><label className="subscene-wide-field">Название<input autoFocus placeholder="Например, Разговор на платформе" value={draft.name} onChange={e=>patch({name:e.target.value})}/></label>
  <h3>Начать с локации</h3><div className="subscene-template-grid">{LOCATION_TEMPLATES.map(t=><button key={t.id} className={draft.kind===t.id?'active':''} onClick={()=>patch({kind:t.id,location:t.name,weather:t.weather,time:t.time})}><Icon name={t.icon} size={29}/><strong>{t.name}</strong><span>{t.detail}</span>{draft.kind===t.id&&<Icon name="Check" className="template-check" size={15}/>}</button>)}</div>
  <div className="subscene-form-grid"><label>Название места<input value={draft.location} onChange={e=>patch({location:e.target.value})}/></label><label>Время суток<select value={draft.time} onChange={e=>patch({time:e.target.value})}>{['Рассвет','День','Закат','Ночь'].map(x=><option key={x}>{x}</option>)}</select></label><label>Погода<select value={draft.weather} onChange={e=>patch({weather:e.target.value})}>{['Ясно','Дождь','Гроза','Туман','Снег'].map(x=><option key={x}>{x}</option>)}</select></label></div>
  <h3>Кто присутствует</h3><div className="subscene-cast">{project.objects.filter(o=>o.type==='Персонаж'&&!o.subsceneId&&o.active!==false).map(o=><label key={o.id}><input type="checkbox" checked={draft.characters.includes(o.id)} onChange={e=>patch({characters:e.target.checked?[...draft.characters,o.id]:draft.characters.filter(id=>id!==o.id)})}/><Icon name="PersonStanding" style={{color:o.color}}/>{o.name}</label>)}{!project.objects.some(o=>o.type==='Персонаж'&&!o.subsceneId)&&<span>Персонажей можно добавить позже в редакторе сцены.</span>}</div>
  <label className="subscene-wide-field">Первая реплика<textarea rows={2} value={draft.firstText} onChange={e=>patch({firstText:e.target.value})}/></label>
  <h3>Место в истории</h3><div className="subscene-placement"><label><input type="radio" name="scene-placement" checked={draft.placement==='separate'} onChange={()=>patch({placement:'separate'})}/><span>Создать отдельно<small>Подключить переходом позже</small></span></label><label><input type="radio" name="scene-placement" checked={draft.placement==='after'} disabled={beat.kind==='end'} onChange={()=>patch({placement:'after'})}/><span>{beat.kind==='choice'?'Вставить после ответа':'Вставить после текущей реплики'}<small>{beat.id} · {beat.text.slice(0,70)}</small></span></label></div>
  {draft.placement==='after'&&beat.kind==='choice'&&<label className="subscene-wide-field">Ответ игрока<select value={draft.choiceId} onChange={e=>patch({choiceId:e.target.value})}><option value="" disabled>Выберите ответ</option>{beat.choices.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label>}
  <div className="subscene-create-summary"><Icon name="Route" size={19}/><span>{draft.placement==='after'?'Текущая реплика / ответ → новая сабсцена → прежнее продолжение':'Новая сабсцена появится отдельно на карте'}<small>Будут созданы первая реплика, основная камера и объекты выбранной локации.</small></span></div>
  {error&&<p className="subscene-form-error" role="alert">{error}</p>}<footer className="subscene-create-footer"><Button icon="Plus" className="subscene-primary" onClick={create}>Создать сабсцену</Button><span>После создания откроется её 3D-сцена.</span></footer></fieldset>
 </>:view==='links'?<TransitionEditor project={project} scene={scene} links={links} running={running} onConnect={onConnect} onDisconnect={onDisconnect} onOpenBeat={onOpenBeat}/>:<>
  <div className="subscene-edit-heading"><div><small>{scene.location}</small><h2>{scene.name}</h2></div><Button icon="Copy" disabled={running} onClick={()=>onDuplicate(scene.id)}>Дублировать</Button></div>
  <div className="subscene-open-actions"><Button icon="Workflow" onClick={()=>onOpenBeat(scene.entry)}>Открыть сценарий <small>{lines.length}</small></Button><Button icon="Box" onClick={onScene}>Редактировать 3D-сцену</Button><Button icon="Video" onClick={onCameras}>Камеры <small>{scene.cameras?.length||0}</small></Button></div>
  <fieldset disabled={running}><div className="subscene-form-grid two"><label>Название сабсцены<CommitInput value={scene.name} onCommit={name=>{if(!name.trim())return false;onPatch({name:name.trim()});}}/></label><label>Название места<CommitInput value={scene.location} onCommit={location=>onPatch({location})}/></label></div><label className="subscene-wide-field">Заметка для автора<CommitInput textarea value={scene.description||''} placeholder="Что происходит в этом фрагменте?" onCommit={description=>onPatch({description})}/></label>
  <div className="subscene-form-grid"><label>Шаблон локации<select value={scene.kind} onChange={e=>onKind(e.target.value)}>{LOCATION_TEMPLATES.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Погода<select value={scene.weather} onChange={e=>onPatch({weather:e.target.value})}>{['Ясно','Дождь','Гроза','Туман','Снег'].map(x=><option key={x}>{x}</option>)}</select></label><label>Время суток<select value={scene.time} onChange={e=>onPatch({time:e.target.value})}>{['Рассвет','День','Закат','Ночь'].map(x=><option key={x}>{x}</option>)}</select></label></div><p className="subscene-field-note">Смена локации обновляет декорации шаблона и основной кадр. Сценарий и персонажи сохраняются.</p>
  <h3>Начало сабсцены</h3><label className="subscene-wide-field">С какой реплики начинать<select value={scene.entry} onChange={e=>onEntry(e.target.value,reroute)}>{lines.map(b=><option value={b.id} key={b.id}>{b.speaker} · {b.text.slice(0,85)}</option>)}</select></label><label className="subscene-entry-option"><input type="checkbox" checked={reroute} onChange={e=>setReroute(e.target.checked)}/>Обновить переходы на прежнее начало ({incoming.filter(l=>l.to===scene.entry).length})</label>
  <h3>Персонажи в этой сабсцене</h3><div className="subscene-cast">{cast.map(o=><label key={o.id}><input type="checkbox" disabled={o.active===false} checked={o.active!==false&&isObjectInScene(o,scene)} onChange={e=>onPatch({excludedObjectIds:e.target.checked?(scene.excludedObjectIds||[]).filter(id=>id!==o.id):[...new Set([...(scene.excludedObjectIds||[]),o.id])]})}/><Icon name="PersonStanding" style={{color:o.color}}/>{o.name}{o.active===false&&<small>отключён в проекте</small>}</label>)}</div></fieldset>
  <div className="subscene-link-summary"><Icon name="GitBranch"/><div><strong>{incoming.length} входящих · {outgoing.length} исходящих переходов</strong><small>{incoming.length?'Переходы могут вести на начало или на конкретную реплику.':'В эту сабсцену пока нет переходов. Её можно проверить отдельным запуском.'}</small></div><Button icon="ArrowRight" onClick={()=>setView('links')}>Настроить</Button></div>
  <section className="subscene-chapters"><h3>Содержимое</h3>{project.chapters.filter(c=>c.subsceneId===scene.id).map(c=><button key={c.id} onClick={()=>onOpenBeat(c.beats[0]?.id||scene.entry)}><Icon name="ListTree"/><span>{c.name}</span><small>{c.beats.length} блоков</small><Icon name="ChevronRight" size={14}/></button>)}</section><p className="subscene-save-note"><Icon name="Check" size={13}/>Изменения сохраняются автоматически · Ctrl+Z — отменить</p>
 </>}</main></div>}
 </div>;
}
function CommitInput({value,onCommit,textarea,...props}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);const Tag=textarea?'textarea':'input';return <Tag {...props} value={draft} rows={textarea?2:undefined} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==value&&onCommit(draft)===false)setDraft(value);}} onKeyDown={e=>{if(!textarea&&e.key==='Enter')e.currentTarget.blur();}}/>;}
function TransitionEditor({project,scene,links,running,onConnect,onDisconnect,onOpenBeat}){
 const [source,setSource]=useState(scene.id),[search,setSearch]=useState(''),[endpoint,setEndpoint]=useState(''),[target,setTarget]=useState(project.subscenes.find(s=>s.id!==scene.id)?.id||'');
 useEffect(()=>{setSource(scene.id);setSearch('');setEndpoint('');setTarget(project.subscenes.find(s=>s.id!==scene.id)?.id||'');},[scene.id]);
 const endpoints=beatsInScene(project,source).filter(b=>b.kind!=='end').flatMap(b=>b.kind==='choice'?b.choices.map(c=>({id:b.id+'|'+c.id,beat:b,choice:c,label:`${b.text.slice(0,35)} → ${c.label}`})):[{id:b.id+'|',beat:b,label:`${b.speaker} · ${b.text.slice(0,80)}`}]),selected=endpoints.find(e=>e.id===endpoint),oldNext=selected?.choice?.next||(!selected?.choice?selected?.beat.next:null),oldScene=project.subscenes.find(s=>beatsInScene(project,s.id).some(b=>b.id===oldNext));
 return <><div className="subscene-edit-heading"><div><small>СВЯЗИ ИСТОРИИ</small><h2>Переходы · {scene.name}</h2></div></div><section className="subscene-connection-builder"><h3><Icon name="GitBranch"/>Подключить к началу сабсцены</h3><fieldset disabled={running}><div className="subscene-form-grid two"><label>Откуда<select value={source} onChange={e=>{setSource(e.target.value);setSearch('');setEndpoint('');if(target===e.target.value)setTarget(project.subscenes.find(s=>s.id!==e.target.value)?.id||'');}}>{project.subscenes.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Куда<select value={target} onChange={e=>setTarget(e.target.value)}><option value="" disabled>Выберите сабсцену</option>{project.subscenes.filter(s=>s.id!==source).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label></div><label className="subscene-wide-field">Найти реплику или ответ<input type="search" placeholder="Текст реплики, имя персонажа или ответ…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="subscene-wide-field subscene-endpoint">После какой реплики или ответа<select value={endpoint} onChange={e=>setEndpoint(e.target.value)}><option value="" disabled>Выберите точку перехода</option>{endpoints.filter(e=>e.id===endpoint||(e.beat.text+' '+e.beat.speaker+' '+(e.choice?.label||'')).toLowerCase().includes(search.toLowerCase())).map(e=><option value={e.id} key={e.id}>{e.label}</option>)}</select></label>{selected&&<p className="subscene-connection-preview">Сейчас: {oldScene?oldScene.name:'нет продолжения'} → станет: {project.subscenes.find(s=>s.id===target)?.name||'выберите назначение'}{selected.choice&&<small>Условие ответа сохраняется: {selected.choice.condition==='trust'?`доверие ≥ ${selected.choice.threshold??3}`:selected.choice.condition==='always'?'всегда доступен':selected.choice.condition}.</small>}</p>}<Button className="subscene-primary" icon="Link" disabled={!selected||!target} onClick={()=>onConnect(selected.beat.id,selected.choice?.id,target)}>Сохранить переход</Button></fieldset></section>
  <h3>Текущие связи <small>{links.length}</small></h3><div className="subscene-link-list">{links.map(l=><article key={l.from+'|'+(l.choiceId||'')}><Icon name={l.target===scene.id?'CornerDownLeft':'CornerUpRight'}/><div><strong>{project.subscenes.find(s=>s.id===l.source)?.name} <Icon name="ArrowRight" size={12}/> {project.subscenes.find(s=>s.id===l.target)?.name||'Реплика удалена'}</strong><p>{l.beat.text.slice(0,85)}{l.choiceId?' · '+l.label:''}</p><small>{l.target===scene.id?'Входящий':'Исходящий'} · {l.choiceId?(l.condition==='always'?'ответ без условия':l.condition==='trust'?`доверие ≥ ${l.threshold??3}`:l.condition):'после реплики'}</small></div><Button icon="Pencil" title="Изменить переход" disabled={running} onClick={()=>{setSource(l.source);setSearch('');setEndpoint(l.from+'|'+(l.choiceId||''));setTarget(l.target||'');}}/><Button icon="ArrowUpRight" title="Открыть исходную реплику" onClick={()=>onOpenBeat(l.from)}/><Button icon="X" title="Убрать этот переход" disabled={running} onClick={()=>onDisconnect(l.from,l.choiceId,l.to)}/></article>)}</div>{!links.length&&<p className="subscene-field-note">Сабсцена пока не связана с другими. Выберите источник и назначение выше — связь появится на карте.</p>}</>;
}
