import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {AUDIO_ASSETS,upgradeProject,allBeats} from '../src/studioModel.js';
import {SoundDesk} from '../src/audio.js';
import {BufferPlayer} from '../src/AudioPlayer.js';
import {PreviewRuntime} from '../src/runtime.js';
import {gameCamera,objectPosition} from '../src/sceneEffects.js';
const tick=(ms=5)=>new Promise(r=>setTimeout(r,ms));
class Audio extends EventTarget {constructor(){super();this.volume=1;this.duration=10;this.currentTime=0;}play(){return Promise.resolve();}pause(){}}

test('every supplied audio points to an existing audio file, including user WAV replacement',()=>{for(const asset of AUDIO_ASSETS){const url=new URL('../public/sound/'+asset.file,import.meta.url);assert.ok(existsSync(url),asset.file);const h=readFileSync(url).subarray(0,12);assert.ok(h.toString().startsWith('RIFF')||h.toString().startsWith('ID3')||h[0]===255,asset.file);}assert.ok(AUDIO_ASSETS[0].file.endsWith('.wav'));});
test('fade out preserves fader, resume restores audible gain, late old end cannot remove new duck',async()=>{const desk=new SoundDesk(()=>new Audio());desk.play('music-main',{key:'bg',volume:.42});await tick();await desk.fade('bg',0,.01);assert.equal(desk.get('bg').volume,.42);assert.equal(desk.get('bg').audio.volume,0);desk.stop('bg');desk.resume('bg');await tick();assert.equal(desk.get('bg').audio.volume,.42);desk.play('voice-bob',{key:'v'});await tick();const old=desk.get('v').audio;desk.play('voice-alice',{key:'v'});await tick();old.dispatchEvent(new Event('ended'));assert.ok(desk.ducks.has('v'));desk.stopAll();});
test('failed audio exposes its cause and completes pending wait',async()=>{const desk=new SoundDesk(()=>{const a=new Audio();a.play=()=>Promise.reject(new Error('decode failed'));return a;});await desk.play('voice-bob');assert.equal(desk.get('voice-bob').status,'error');assert.match(desk.get('voice-bob').error,/decode failed/);desk.stopAll();});
test('live loop is forwarded to source and cancelled decode cannot start a source',async()=>{let resolve,starts=0;const source={connect(){},disconnect(){},start(){starts++;},stop(){}};const output={unlock:()=>Promise.resolve(),load:()=>new Promise(r=>resolve=r),context:{currentTime:0,createBufferSource:()=>source,createGain:()=>({gain:{value:1},connect(){},disconnect(){}})},master:{},normalized:true};const a=new BufferPlayer('url',output);const task=a.play();await tick();a.pause();resolve({buffer:{duration:2},gain:1});await task;assert.equal(starts,0);a.source=source;a.loop=true;assert.equal(source.loop,true);a.pause();});
test('stopped moves preserve interpolated start, motion samples cannot collide silently',async()=>{const p=upgradeProject(),rt=new PreviewRuntime(new SoundDesk(()=>new Audio()));p.events.find(e=>e.id==='visual-walk').groups[0].actions[0].duration=.3;const task=rt.previewEvent(p,'visual-walk','a1');await tick(90);const i=Object.values(rt.snapshot.instances).find(i=>i.eventId==='visual-walk');assert.ok(rt.snapshot.world.motions.alice.progress>0);await rt.previewEvent(p,'visual-return','a1');assert.match(rt.snapshot.error,/ещё выполняется/);rt.controlInstance(i.id,'stop');await task;const before=objectPosition(p.objects.find(o=>o.id==='alice'),rt.snapshot.world,'living');const next=rt.previewEvent(p,'visual-return','a1');await tick(5);const motion=rt.snapshot.world.motions.alice;assert.deepEqual(motion.from,before.toArray());rt.stop();await next;});
test('game cameras are inside scenes and interaction targets receive an inspection view',()=>{for(const kind of ['living','garden','station']){const [position]=gameCamera(kind,{});assert.ok(position[1]<1.8);assert.ok(Math.abs(position[0])<3);assert.ok(position[2]<=3);}assert.notDeepEqual(gameCamera('garden',{interactionTarget:'garden-note'}),gameCamera('garden',{}));});
test('visual examples are idempotent and do not rewrite the story',()=>{const p=upgradeProject(),ids=allBeats(p).map(b=>b.id);assert.equal(p.events.filter(e=>e.id.startsWith('visual-')).length,30);assert.deepEqual(upgradeProject(p),p);assert.deepEqual(allBeats(upgradeProject(p)).map(b=>b.id),ids);});
