import test from 'node:test';
import assert from 'node:assert/strict';
import {createEmptyProject} from '../src/projectLifecycle.js';
import {createCharacter} from '../src/characterModel.js';
import {applyGamePreset,newItem,newRule,validateGameplay} from '../src/gameplayModel.js';
import {PreviewRuntime} from '../src/runtime.js';
import {SoundDesk} from '../src/audio.js';
import {callBlueprint,evaluateExpression,writePath} from '../src/blueprintFunctions.js';
import {moveBody,rayBox} from '../src/gamePhysics.js';
import {gameSave,restoreGameSave,validateGameSave} from '../src/gameSave.js';
import {widgetValue,boundText,widgetVisible} from '../src/widgetBindings.js';
import {makeAction} from '../src/model.js';
import {validateStudio} from '../src/studioModel.js';
import {typedValue} from '../src/choiceModel.js';
function fixture(){const p=createEmptyProject('Механики'),scene=p.subscenes[0],player=createCharacter(p,scene.id,'Герой');scene.kind='empty';player.collision={enabled:true,custom:true,size:[.6,1.6,.6],offset:[0,.8,0]};applyGamePreset(p,'fps',player.id);const b=p.chapters[0].beats[0];b.kind='gameplay';p.gameplay.hudWidgetId=p.ui.hud;const rt=new PreviewRuntime(new SoundDesk(()=>({play:()=>Promise.resolve(),pause(){},addEventListener(){},removeEventListener(){},duration:1,currentTime:0})));return {p,rt,player,scene,b};}
const settle=()=>new Promise(r=>setTimeout(r,70));
test('swept controller slides on walls, lands on floors and jumps only when grounded',async()=>{const {p,rt,player,scene}=fixture();try{await rt.start(p,scene.entry);rt.playerStep([1,0,0],.05);assert.ok(rt.game.position(player.id)[0]>0);assert.equal(rt.game.state.bodies[player.id].grounded,true);rt.game.command('jump');const vy=rt.game.state.bodies[player.id].velocity[1];rt.playerStep([0,0,0],.05);assert.ok(rt.game.position(player.id)[1]>0);rt.game.command('jump');assert.ok(rt.game.state.bodies[player.id].velocity[1]<vy);rt.togglePause();const y=rt.game.position(player.id)[1];rt.playerStep([0,0,0],.05);assert.equal(rt.game.position(player.id)[1],y);}finally{rt.stop();}
 const object={id:'body',type:'Меш',collision:{custom:true,size:[1,1,1],offset:[0,0,0]}},wall={id:'wall',box:{min:[2,-10,-10],max:[3,10,10]}};const result=moveBody(object,[0,0,0],[10,0,3],[wall],'scene');assert.equal(result.position[0],1.5);assert.equal(result.position[2],3);assert.deepEqual(result.contacts,['wall']);assert.equal(rayBox([0,0,0],[1,0,0],wall.box,1),null);});
test('inventory stacking, full slots, equip, recipe rollback and consumable healing',async()=>{const {p,rt,scene,player}=fixture();p.gameplay.items=[{...newItem(),id:'a',name:'A',stackLimit:2,slot:'hand'},{...newItem(),id:'b',name:'B',heal:20,consumable:true},{...newItem(),id:'c',name:'C'}];p.gameplay.inventory.slots=2;p.gameplay.recipes=[{id:'craft',ingredients:[{itemId:'a',count:1},{itemId:'b',count:1}],resultId:'c',count:1}];try{await rt.start(p,scene.entry);rt.game.addItem('a',2);rt.game.addItem('b');assert.throws(()=>rt.game.addItem('a'),/нет свободного места/);assert.equal(rt.game.count('a'),2);rt.game.equip('a');assert.equal(rt.game.state.equipment.hand,'a');rt.game.combine('craft');assert.equal(rt.game.count('c'),1);const before=JSON.stringify(rt.game.state.inventory);assert.throws(()=>rt.game.combine('craft'),/Не хватает/);assert.equal(JSON.stringify(rt.game.state.inventory),before);rt.game.removeItem('a');assert.equal(rt.game.state.equipment.hand,undefined);rt.game.addItem('b');rt.game.damage(player.id,30);await rt.game.useItem('b');assert.equal(rt.game.state.actors[player.id].hp,90);}finally{rt.stop();}});
test('rules independently dispatch enter, exit, timer and tick; pause freezes all clocks',async()=>{const {p,rt,scene,player}=fixture();p.variables.entered=0;p.variables.exited=0;p.variables.ticks=0;p.events=['entered','exited','ticks'].map(id=>({id,name:id,owner:'GameSession',retention:'AUTO_CLOSE_ON_FLOW_END',groups:[{id:id+'-g',actions:[{...makeAction('variable',id,1),operation:'add',valueType:'number'}]}]}));p.gameplay.rules=[{...newRule(),id:'enter',trigger:'enter',center:[0,.8,0],size:[2,3,2],eventId:'entered',once:false},{...newRule(),id:'exit',trigger:'exit',center:[0,.8,0],size:[2,3,2],eventId:'exited',once:false},{...newRule(),id:'tick',trigger:'tick',seconds:.1,eventId:'ticks',once:false}];try{await rt.start(p,scene.entry);rt.game.tick(.05);await settle();assert.equal(rt.snapshot.variables.entered,1);rt.snapshot.world.positions[player.id]=[3,0,0];rt.game.tick(.05);await settle();assert.equal(rt.snapshot.variables.exited,1);assert.equal(rt.snapshot.variables.ticks,1);rt.togglePause();const clock=rt.game.state.clock;rt.game.tick(.05);assert.equal(rt.game.state.clock,clock);}finally{rt.stop();}});
test('projectile hits a collider along its whole step and reload restores ammo from reserve',async()=>{const {p,rt,scene}=fixture();const target={id:'target',name:'Цель',type:'Меш',active:true,subsceneId:scene.id,collision:{enabled:true,custom:true,size:[1,2,1],offset:[0,1,0]},transforms:{[scene.id]:{position:[0,0,-3],rotation:[0,0,0],scale:[1,1,1]}}};p.objects.push(target);p.gameplay.actors.target={team:'enemy',maxHP:50};Object.assign(p.gameplay.weapons[0],{mode:'projectile',projectileSpeed:100,damage:25,magazine:1,reserve:2,reloadTime:.1});try{await rt.start(p,scene.entry);rt.game.shoot({origin:[0,1,-1],direction:[0,0,-1]});assert.equal(rt.game.state.projectiles.length,1);rt.game.tick(.05);assert.equal(rt.game.state.actors.target.hp,25);assert.equal(rt.game.state.projectiles.length,0);assert.equal(rt.game.shoot(),false);rt.game.reload();rt.game.tick(.05);rt.game.tick(.05);assert.equal(rt.game.state.weapons[rt.game.state.weaponId].ammo,1);assert.equal(rt.game.state.weapons[rt.game.state.weaponId].reserve,1);}finally{rt.stop();}});
test('function graphs have isolated args/locals, nested calls, structs, arrays and bounded loops',async()=>{const vars={stats:{score:0},list:[]},p={functions:[{id:'double',parameters:[{name:'n',type:'number',default:0}],locals:{},entry:'r',nodes:[{id:'r',kind:'return',value:{op:'mul',a:{op:'get',path:'args.n'},b:2}}]},{id:'main',parameters:[],locals:{answer:0},entry:'c',nodes:[{id:'c',kind:'call',functionId:'double',args:{n:5},output:'local.answer',next:'s'},{id:'s',kind:'set',path:'global.stats.score',value:{op:'get',path:'local.answer'},next:'a'},{id:'a',kind:'array',operation:'push',path:'global.list',value:{op:'struct',fields:{score:{op:'get',path:'local.answer'}}},next:'r'},{id:'r',kind:'return',value:{op:'field',a:{op:'at',a:{op:'get',path:'global.list'},b:0},field:'score'}}]}]};assert.equal(await callBlueprint(p,'main',{},vars,()=>{}),10);assert.equal(vars.stats.score,10);assert.deepEqual(vars.list,[{score:10}]);assert.deepEqual(p.functions[1].locals,{answer:0});assert.throws(()=>writePath(vars,'__proto__.bad',true),/Недопустимое/);assert.throws(()=>evaluateExpression({op:'div',a:1,b:0},{}),/Недопустимая/);p.functions.push({id:'loop',parameters:[],entry:'s',nodes:[{id:'s',kind:'set',path:'global.x',value:0,next:'s'}]});await assert.rejects(callBlueprint(p,'loop',{},vars,()=>{}),/лимит шагов/);assert.deepEqual(typedValue('[1,2]','array'),[1,2]);assert.throws(()=>typedValue('{}','array'),/массивом/);});
test('save restores HP, position, inventory, timers and graph state without replaying events',async()=>{const {p,rt,scene,player}=fixture();try{await rt.start(p,scene.entry);rt.game.damage(player.id,35);rt.snapshot.world.positions[player.id]=[2,1,2];rt.game.command('startTimer',{timerId:'alarm',seconds:5});const save=JSON.parse(JSON.stringify(gameSave(rt)));rt.game.damage(player.id,20);rt.snapshot.world.positions[player.id]=[0,0,0];await restoreGameSave(rt,save);assert.equal(rt.game.state.actors[player.id].hp,65);assert.deepEqual(rt.game.position(player.id),[2,1,2]);assert.equal(rt.game.state.timers.alarm.remaining,5);assert.equal(rt.snapshot.phase,'PLAYING');assert.throws(()=>validateGameSave(p,{...save,projectId:'other'}),/не подходит/);assert.throws(()=>validateGameSave(p,{...save,world:{...save.world,game:{...save.world.game,inventory:[{itemId:'missing',count:1}]}}}),/Инвентарь/);}finally{rt.stop();}});
test('widget bindings read fields and independently format text, progress and visibility',()=>{const context={variables:{stats:{score:12},show:true},game:{actors:{hero:{hp:75}}}};assert.equal(widgetValue(context,{source:'game',path:'actors.hero.hp'}),75);assert.equal(boundText({binding:{source:'variable',path:'stats.score',format:'Score: {value}'}},context,'fallback'),'Score: 12');assert.equal(widgetVisible({showIf:{source:'variable',path:'show'}},context),true);assert.equal(widgetVisible({showIf:{source:'variable',path:'show',negate:true}},context),false);});
test('malformed game data and dangling rule references are diagnosed before play',()=>{const {p}=fixture();assert.deepEqual(validateStudio(p),[]);p.gameplay.rules.push({...newRule(),eventId:'missing'});assert.ok(validateGameplay(p).some(i=>i.detail==='Событие правила удалено.'));p.gameplay.controller.speed=-1;assert.ok(validateGameplay(p).some(i=>i.id==='game-controller'));});
test('story graph displays rule transitions from playable nodes without changing their next links',async()=>{const {buildStoryFlow}=await import('../src/storyFlowModel.js');const {p,b}=fixture();p.chapters[0].beats.push({id:'over',kind:'end',text:'Game Over',bindings:[],next:null});p.gameplay.rules=[{...newRule(),id:'death',trigger:'death',nextBeatId:'over'}];const model=buildStoryFlow(p),edge=model.edges.find(e=>e.data.gameRule);assert.equal(edge.source,b.id);assert.equal(edge.target,'over');assert.equal(edge.deletable,false);assert.equal(b.next,null);});
