import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parseProjectFile} from '../src/projectLifecycle.js';
import {readProject} from '../src/projectFiles.js';
import {validateStudio} from '../src/studioModel.js';
import {PreviewRuntime} from '../src/runtime.js';
import {SoundDesk} from '../src/audio.js';
const template=name=>parseProjectFile(readFileSync(new URL('../public/game-templates/'+name+'.sacura-template.json',import.meta.url),'utf8')).project;
class Audio extends EventTarget {duration=1;currentTime=0;volume=1;play(){return Promise.resolve();}pause(){}}
const runtime=()=>new PreviewRuntime(new SoundDesk(()=>new Audio()));
const settle=async(rt)=>{for(let i=0;i<200&&(rt.game.flights.size||!rt.snapshot.ready);i++)await new Promise(r=>setTimeout(r,10));assert.equal(rt.snapshot.error,null);assert.equal(rt.game.flights.size,0);};
for(const name of ['point-and-click','shooter'])test(name+' imports and round trips with clean engine diagnostics',()=>{const p=template(name);assert.deepEqual(validateStudio(p),[]);assert.deepEqual(readProject(JSON.stringify(p)),p);assert.ok(p.functions.length);assert.ok(p.widgets.some(w=>w.kind==='hud'));assert.ok(p.gameplay.enabled);});
for(const order of [['quest-key','quest-note'],['quest-note','quest-key']])test('quest native inventory and recipe complete in either pickup order '+order,async()=>{const p=template('point-and-click'),rt=runtime();try{await rt.start(p,p.subscenes[0].entry);await rt.advance();assert.equal(rt.snapshot.phase,'PLAYING');for(const id of order){rt.snapshot.world.positions['quest-hero']=rt.game.position(id).map((v,i)=>i===1?0:v);assert.equal(rt.game.interact(id),true);await settle(rt);}assert.equal(rt.game.count('key'),1);assert.equal(rt.game.count('note'),1);assert.equal(rt.game.interact(order[0]),false);assert.equal(rt.snapshot.variables.journal.length,2);rt.game.combine('prepare-key');assert.equal(rt.game.count('prepared-key'),1);assert.equal(rt.game.count('key'),0);await rt.game.useItem('prepared-key');assert.equal(rt.game.count('prepared-key'),0);assert.equal(rt.snapshot.beatId,'quest-yard-intro');assert.equal(rt.snapshot.world.location,'quest-yard');await rt.advance();rt.snapshot.world.positions['quest-hero']=[.5,0,-.8];rt.game.interact('quest-relic');await settle(rt);assert.equal(rt.snapshot.beatId,'quest-win');assert.equal(rt.snapshot.variables.relicFound,true);}finally{rt.stop();}});
test('finished FPS level requires a reload and awards points for all five enemies',async()=>{const p=template('shooter'),rt=runtime();try{await rt.start(p,p.subscenes[0].entry);await rt.advance();assert.equal(rt.snapshot.phase,'PLAYING');for(const id of Object.keys(p.gameplay.actors).filter(id=>id!=='shooter-hero')){while(!rt.game.state.actors[id].dead){if(!rt.snapshot.variables.ammo){rt.game.reload();for(let i=0;i<24;i++)rt.game.tick(.05);}const target=rt.game.position(id);assert.equal(rt.game.shoot({origin:[target[0],target[1]+1,target[2]+1],direction:[0,0,-1]}),true);rt.game.state.clock+=.23;}}await settle(rt);assert.equal(rt.snapshot.variables.kills,5);assert.equal(rt.snapshot.beatId,'shooter-win');assert.equal(rt.snapshot.variables.results.defeated.length,5);assert.equal(rt.snapshot.variables.score,500);assert.ok(rt.game.state.weapons.pistol.reserve<40);}finally{rt.stop();}});

test('native shooter events switch weapons, heal only when needed and update the pickup HUD',async()=>{const p=template('shooter'),rt=runtime();try{await rt.start(p,p.subscenes[0].entry);await rt.advance();await rt.uiAction('event',{id:'heal',eventId:'heal-player'});assert.equal(rt.game.count('medkit'),1);assert.equal(rt.snapshot.variables.medkits,1);await rt.inputAction({actionId:'launcher-select',phase:'triggered',value:1,device:'keyboard'});assert.equal(rt.game.state.weaponId,'launcher');assert.equal(rt.snapshot.variables.weaponName,'Гранатомёт');await rt.uiAction('event',{id:'pistol',eventId:'equip-pistol'});assert.equal(rt.game.state.weaponId,'pistol');assert.equal(rt.snapshot.variables.weaponName,'Пистолет');rt.game.damage('shooter-hero',75);await settle(rt);assert.equal(rt.snapshot.variables.lowHealth,true);await rt.inputAction({actionId:'medkit-use',phase:'triggered',value:1,device:'keyboard'});assert.equal(rt.snapshot.variables.hp,65);assert.equal(rt.snapshot.variables.lowHealth,false);assert.equal(rt.snapshot.variables.medkits,0);assert.equal(rt.game.count('medkit'),0);await rt.uiAction('event',{id:'heal',eventId:'heal-player'});assert.equal(rt.snapshot.variables.hp,65);rt.snapshot.world.positions['shooter-hero']=[-5,0,3];assert.equal(rt.game.interact('arena-medkit'),true);await settle(rt);assert.equal(rt.game.count('medkit'),1);assert.equal(rt.snapshot.variables.medkits,1);assert.equal(rt.snapshot.world.visible['medkit-cross-horizontal'],false);}finally{rt.stop();}});

test('AI hurts player, death enters Game Over without enemy points, and restart resets the entire loadout',async()=>{const p=template('shooter'),rt=runtime();try{await rt.start(p,p.subscenes[0].entry);await rt.advance();rt.snapshot.world.positions['shooter-hero']=[0,0,-.5];rt.game.tick(.05);assert.equal(rt.game.state.actors['shooter-hero'].hp,90);await rt.uiAction('event',{id:'heal',eventId:'heal-player'});assert.equal(rt.game.state.actors['shooter-hero'].hp,100);assert.equal(rt.game.count('medkit'),0);rt.game.damage('shooter-hero',100);await settle(rt);assert.equal(rt.snapshot.beatId,'shooter-game-over');assert.deepEqual(rt.snapshot.variables.results.defeated,[]);assert.equal(rt.snapshot.variables.score,0);await rt.start(p,p.subscenes[0].entry);await rt.advance();assert.equal(rt.game.state.actors['shooter-hero'].hp,100);assert.equal(rt.game.count('medkit'),1);assert.equal(rt.game.state.kills,0);assert.equal(rt.snapshot.variables.medkits,1);assert.equal(rt.game.state.weaponId,'pistol');assert.equal(rt.snapshot.variables.ammo,8);}finally{rt.stop();}});

test('finished shooter save restores weapon, ammo, healing, score and defeated actors without restarting combat',async()=>{const p=template('shooter'),rt=runtime(),saved=new Map();rt.storage={setItem:(k,v)=>saved.set(k,v),getItem:k=>saved.get(k)};try{await rt.start(p,p.subscenes[0].entry);await rt.advance();rt.game.damage('enemy-1',50);rt.game.damage('shooter-hero',50);await settle(rt);await rt.uiAction('event',{id:'heal',eventId:'heal-player'});await rt.uiAction('event',{id:'launcher',eventId:'equip-launcher'});rt.game.shoot({direction:[0,1,0]});rt.togglePause();const before=structuredClone(rt.snapshot.variables);assert.equal(before.weaponName,'Гранатомёт');assert.equal(before.hp,90);assert.equal(before.medkits,0);assert.equal(before.score,100);assert.equal(before.ammo,2);rt.saveGame();assert.equal(saved.size,1);await rt.start(p,p.subscenes[0].entry);await rt.loadGame();assert.equal(rt.snapshot.beatId,'shooter-combat');assert.deepEqual(rt.snapshot.variables,before);assert.equal(rt.game.state.weaponId,'launcher');assert.equal(rt.game.state.actors['enemy-1'].dead,true);assert.equal(rt.game.count('medkit'),0);}finally{rt.stop();}});
